### ISSUE TITLE
Invalid PEM formatted message

### ISSUE THREAD

**Issue by sh0eps** [alexandercerutti/passkit-generator#10]
Hi !

I'm trying to use your lib but I'm not able to get it working.

I try to run a basic example

```
const { Pass } = require("passkit-generator");
 
let pass = new Pass({
    model: "./passModels/myFirstModel",
    certificates: {
        wwdr: "./certs/wwdr.pem",
        signerCert: "./certs/signercert.pem",
        signerKey: {
            keyFile: "./certs/signerkey.pem",
            passphrase: "pass"
        }
    }
});
 
// Adding some settings to be written inside pass.json
pass.localize("fr");
pass.barcode("36478105430"); // Random value
 
// Generate the stream, which gets returned through a Promise
pass.generate()
    .then(stream => {
        console.log(stream);
    })
    .catch(err => {
        console.log(err);
    });
```

I get the following error : 

> Error: Error: Invalid PEM formatted message.
    at readCertificates.then.then.catch (/Users/aflalo/node_modules/passkit-generator/src/pass.js:68:11)

I tried to log the Certificate object created before readind : 

`{ _raw:
   { wwdr: './certs/wwdr.pem',
     signerCert: './certs/signercert.pem',
     signerKey: { keyFile: './certs/signerkey.pem', passphrase: 'pass' } } }`

Any clue ? Thanks

**Comment by alexandercerutti** [comment]
Hi! I'll try to do my best to help you!
Do you have `./certs` folder with the files, do you?
The `Certificate` variable is okay.
The error is related to a bad-formatted PEM file. You have to check if the content of the keys.

Try to execute this command on the `signerkey.pem` and `signercert.pem` and see if they have any content.

```sh
$ openssl x509 -in certificate.pem -noout -text
```
Which procedure did you follow to get the two files? The one for macOS or the one not for macOS?

**Comment by sh0eps** [comment]
Thanks for your quick answer. I notices that the signerkey.pem is wrong. Are you sure about the command to generate it ?

**Comment by sh0eps** [comment]
Ok, I changed something I just don't know why but now it's working...

Thanks !

**Comment by alexandercerutti** [comment]
Well, yeah, I'm sure about the command. You used the "non-macOS-steps", right? Because the command you told me you used, is the same I putted in the "macOS steps". I'd like to better understand for the future. 😊

**Comment by Aitorgb** [comment]
Hi! I have the same problem. 

My code is : 

`let pass = new PKPass(
			{
				model: './card.pass',
				icon: './public/images/icon.png',
				icon2x: './public/images/icon@2x.png',
				logo: './public/images/logo.png'
			},
			{
				wwdr: './certs/wwdrr.pem',
				signerCert: './certs/signercert.pem',
				signerKey: './certs/signerkey.pem'
			}
		);
		pass.type = 'storeCard';
		pass
			.getAsStream()
			.then((stream) => {
				console.log(stream);
			})
			.catch((err) => {
				console.log(err);
			});`

The error is 
`Error: Invalid PEM formatted message.
    at Object.pem.decode (/Users/aitor/Documents/Tangram Publicidad y YOYO/tarjetas-virtuales/virtual-card/node_modules/node-forge/lib/pem.js:192:11)`

I execute this command 
openssl x509 -in filename.pem -noout -text 

The signerKey.pem not working. 

Any clue ? Thanks

**Comment by midoshawky** [comment]
@Aitorgb  Hi did u manage to bypass this? because im facing same issue now signerKey is not opening and it has issue

**Comment by adrienafl** [comment]
Hey, this thread is 4yo. I have no clue about what I did in order to get it work. Good luck 😅

**Comment by alexandercerutti** [comment]
I'm going to lock this conversation, as it is quite old (6 years now), so I invite who thinks is reflecting in this issue, to open a new one in order to receive help. Thank you!
