### ISSUE TITLE
Field order in the loaded pass.json is not preserved

### ISSUE THREAD

**Issue by zhenwenc** [alexandercerutti/passkit-generator#103]
In the generated passes, the fields (eg: `primaryFields`, `secondaryFields`) appear in reverse order compared to the original source in `pass.json`. For example, loading a store card bundle with

```json
...
      "storeCard": {
        "secondaryFields": [
          {
            "key": "name",
            "label": "Name",
            "value": "Jon Snow"
          },
          {
            "key": "dateOfBirth",
            "label": "Date of birth",
            "value": "13 OCT 1980"
          }
        ],
...
```

produces a pass like this

<img width="302" alt="image" src="https://user-images.githubusercontent.com/5435340/154751284-797a498a-7eba-4510-8e8d-f83640e44dc8.png">

---

Here is a simple unit test to reproduce the issue under the `spec/FieldsArray.ts` setup (untested):

```typescript
                it("should preserve field order", () => {
                        expect(fa.push({ key: "t1", value: "v1" })).toBe(1);
                        expect(fa.push({ key: "t2", value: "v2" })).toBe(1);
                        expect(fa.length).toBe(2);
                        expect(fa[0]).toEqual({ key: "t1", value: "v1" });
                        expect(fa[1]).toEqual({ key: "t2", value: "v2" });
                });
```

---

I noticed that it's caused by the `FieldArray#registerWithValidation` is traversing the array items in reverse order.
https://github.com/alexandercerutti/passkit-generator/blob/ccd38262ec69d37b669774aba6812feeb0a16534/src/FieldsArray.ts#L70-L87

Is there any particular reason? I believe it's an unexpected breaking change introduced since v3.

Many thanks in advance!

**Comment by alexandercerutti** [comment]
I never noticed that! I've verified that you are right.

I generally use an inverted loop to have a little bit more performance while looping (even if that might be not that much). I must have been confused with the usage of `push` and broke this thing. This is a quite bad mistake I made when publishing v3.

This is not a breaking change. I mean, that's not the intended behavior: FieldsArray should behave just like an array!

Would you like to open a PR with tests and loop inversion? I'll publish and deprecate the previous versions once this will come out.

Thank you!

**Comment by zhenwenc** [comment]
@alexandercerutti No problem! It's great to hear you are mindful of the performance! 

Created a small PR with the fix (https://github.com/alexandercerutti/passkit-generator/pull/104). 

Thanks!
