### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by kamami** [alexandercerutti/passkit-generator#109]
How can I use this package? Any examples or guides how to install?
I already have all necessary certificates, but do not know how to start.

**Comment by alexandercerutti** [comment]
Hey there @kamami,
when I created this packages I put all myself into making it clear on how to use it, examples, documents and so on. Everything is accessible from the main README.

The fact that you didn't even tried to read the README makes me really really sad. :(

**Comment by kamami** [comment]
I really did read the README until the point: Examples with `getCertificatesContentsSomehow` and `doSomethingWithTheStream`. Do I need to run this script? Or how do I upload the certificates. There are a lot of questions to me...

**Comment by kamami** [comment]
Thank you! Could you just show an example query string for one example? Just to maker sure, I get everything right. So in general I call several URLS in a row with different query parameters to set all the value of the pass? E.g. how would I set the localization?

**Comment by alexandercerutti** [comment]
The url is correct. You probably are not passing the certificates. 

> Certificates paths in examples are linked to a folder certificates in the root of this project which is not provided. To make them work, you'll have to edit both certificates and model path.

You should check the name of the files corresponds with the files the examples are trying to retrieve (check them in `./shared.ts`).

---

Examples are fixed, you cannot pass query parameters if not specified in the Readme notes.

**Comment by kamami** [comment]
Ok great, but how does all this fit together with your great visual designer? Do I export a ticket there and put it into the models folder and then call the url?

**Comment by alexandercerutti** [comment]
Yes

**Comment by alexandercerutti** [comment]
@kamami please note that you are asking too much. I mean, most of the things you asking me can be discovered with a bit of searching. I'm here to answer to questions and help people (especially those who donate) but not to create the app for you.

Getting back to your issue, I don't know how to help you. I don't know if you changed something, if you did anything, what is your model nor anything else. "Type" is the key in pass.json "boardingPass" or "storeCard", and so on. You can refer to Apple documentation linked in the main Readme.
