### ISSUE TITLE
Storing PEM Certificates on Heroku

### ISSUE THREAD

**Issue by ahsan-AJ** [alexandercerutti/passkit-generator#11]
I am trying to deploy the express server on heroku. Can anyone suggest how do I store my certificates? Should I directly store the .pem files on Heroku or should I add these .pem files and env variables. 

P.S: I tried adding these .pem files as environment variables but I am getting error like this

"Error: Invalid certificate loaded. 04GpZnMBxRpVzscYqC tGwPDBUf -----END CERTIFICATE----- does not exist."

**Comment by ahsan-AJ** [comment]
I see. But shouldn't it be able to read the certificates as string so we can store them as environment variables as storing physical files like this can be risky ?

**Comment by alexandercerutti** [comment]
Yeah, why not. I never considered such option. I have to understand how can a developer select the "reading behavior". Any suggestions?

**Comment by ahsan-AJ** [comment]
@alexandercerutti I think (and please correct me if I am wrong), We can make it able the contents as string or by file depending on the type of the property passed to the key.

**Comment by alexandercerutti** [comment]
The fact is that whether you pass a path or a certificate, they are both strings as type.
I'd discard a string length check. I'm more inclined to a property to switch the behavior, but I'm not that sure.

**Comment by alexandercerutti** [comment]
Okay, I had the possibility to test it and it gives empty root and empty ext if the string is a certificate. So I could base the checks on this.

**Comment by ahsan-AJ** [comment]
Okay I will try this as well using the path module.. Will update.

**Comment by alexandercerutti** [comment]
I've created a new branch with this feature: [next](https://github.com/alexandercerutti/passkit-generator/tree/next). Download passkit-generator from there and test if it works (but it should definitely work). 😊

**Comment by ahsan-AJ** [comment]
Ok great. I'll download the branch and start working asap 😊

**Comment by alexandercerutti** [comment]
Hi, @ahsan-AJ! Any news?

**Comment by ahsan-AJ** [comment]
@alexandercerutti Sorry been busy in exams and work. Will resume working on it as soon as I get the time this week. Will update you.

**Comment by alexandercerutti** [comment]
Okay, NP! 😉

**Comment by alexandercerutti** [comment]
I was thinking to release it anyway. Have you had time to test it? @ahsan-AJ

**Comment by aaliakseyenka** [comment]
Hi @alexandercerutti,

looking forward to merging this MR to master, need exactly the same behaviour

**Comment by alexandercerutti** [comment]
Hi @aaliakseyenka, thank you!
Can I ask you to test if it works what I pushed in the [next](https://github.com/alexandercerutti/passkit-generator/tree/next) branch? I have to write tests yet of this. Moreover my Apple Developer Account expired and I don't know if I can generate passes anymore without paying.

**Comment by aaliakseyenka** [comment]
@alexandercerutti I can confirm it is working with new branch, when passing strings instead of file paths

**Comment by alexandercerutti** [comment]
Awesome, @aaliakseyenka! I will merge and release it this evening (UTC). I don't know if I should write some tests, as the keys should be private...

**Comment by aaliakseyenka** [comment]
I will start using it immediately :)

**Comment by alexandercerutti** [comment]
I'm happy to hear this ehe 😊. Meanwhile, do you have any feedback?

**Comment by aaliakseyenka** [comment]
no feedback yet, just started using package today, but will provide if any

**Comment by alexandercerutti** [comment]
Published in v1.5.6.

Closing! Thank you @aaliakseyenka and @ahsan-AJ.
