### ISSUE TITLE
The requested module 'passkit-generator' does not provide an export named 'PKPass'

### ISSUE THREAD

**Issue by mhmdbehairy** [alexandercerutti/passkit-generator#142]
## Running OS
macOS 13.3

## Running Node Version
16

## Description
I get this error when I try to use the package. I have the error only with this package, but not with other packages.

<img width="696" alt="Screenshot 2023-04-20 at 14 32 03" src="https://user-images.githubusercontent.com/46031846/233366720-3856148e-f2e8-45ae-a129-c95a5c1af122.png">

## Expected behavior
I expected no problems with importing.

## Steps to reproduce
1. Import the library in an ES module using `import { PKPass } from 'passkit-generator'`
2. Try to call `new PKPass()`

**Comment by alexandercerutti** [comment]
Hey there @mhmdbehairy, thanks for using passkit-generator!
I tried the other day to use passkit-generator with ESM to build the new tests and I find difficulties in the same way (I ended up building them with CJS).

That's actually related to a mess that happened when Node included the support to ESM.

PKPass gets exported through `module.exports`. That means that NodeJS will find that object through the default in case of ESM.

I've tried with two different examples:

```js
import("./lib/index.js").then((module) => {
    console.log(module);
});
```

In the case above, `module` owns a `default` property which has inside of it a `PKPass` property.

So, at the same way, doing

```
import PKPass from "passkit-generator";
```

will lead to the same result. So you would need to do `PKPass.PKPass`. And, I know, that actually kinda sucks.

The thing is actually the same if you do:

```
import("./lib/PKPass.js").then((module) => {
   console.log(module);
});
```

Here module has `default.default`, which is really really bad.
I honestly don't know if there's a way to fix this behavior in a non-breaking change way.

I was thinking to bring the package to ESM with the v4 but that would be very breaking and I don't know if many people are ready yet to ESM. Still thinking to make a double package.

If you have any idea, let me know.

**Comment by nohehf** [comment]
Hi, I had the same issue, and I have to use it in ESM as all my packages in the project are compiled in ESM. I settled on `PkPass.PkPass`, and it seems to be working fine. Regarding your concerns, I believe most projects are now ESM in their latest versions.

**Comment by alexandercerutti** [comment]
@nohehf It is not really said that most are now in ESM. Transition is very difficult. ESM is not a drop-in replacement for CJS. They are different and they differ in several heavy ways.

I have to understand if I should create a version that exports both CJS and ESM or just ESM.

**Comment by nohehf** [comment]
I did some research on this, and I think you can support both, using two tsconfig files (for `esm` and `cjs`). Then in your `package.json` use conditional exports like:
```JSON
{
    ...
    "exports": {
        "import": "esm-build-entrypoint",
        "require": "cjs-build-entrypoint",
        "default": "esm-build-entrypoint"
    }
}
```

Here is an article about this technique: <https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html> (but you can find many more). Tho It seems to be a bit of a hack.

I really think this hole CJS / ESM situation stinks (to be polite) a lot and is really confusing.
In the end I settled on using:
```TS
import passkit from "passkit-generator";

// ...

const pass = new passkit.PkPass(...)
```
Wich is more elegant and feels ok.
Maybe this could be in the docs?

**Comment by alexandercerutti** [comment]
Yep. It might be worth adding a line in both Readme and wiki.

About ESM and CJS I have to think more about making a hybrid package. Thank you for the resource @nohehf. I agree on it to feel to be a hack.

**Comment by alexandercerutti** [comment]
I've added a reference to the README. This should be enough, until now, to close this issue. Of course, the way you have to import ESM on node sucks, but I don't think there's more I can do *right now*. I probably take some time to rework or implement new features after the WWDC. Last year they didn't bring any new relevant features to passes, so I do expect something this year.
