### ISSUE TITLE
Something wrong with the certificate

### ISSUE THREAD

**Issue by hello0827** [alexandercerutti/passkit-generator#145]
### Running OS
MacOS 10.15.7 

### Running Node Version
v18.2.0

### Description
I've Followed all the instruction in wiki, and all certs should be OK. But I still got the error message. I am using the G4 certificate
I tried to read the cert into buffer first, but still not working.
Many thanks.

Error messge:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5088779/236179604-0b3f9249-e7b5-4440-b0d9-9104443497cb.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/5088779/236178331-e49933a8-0a33-4a20-bcb2-9b3e5f6cc601.png">

I've tested the certificate with the following commands:
`openssl pkey -in signerKey.pem -passin pass:<hidden> `: ok, the private key is printed
`openssl x509 -inform PEM -in AppleWWDRCAG4.pem -noout -text`:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5088779/236176603-403d4122-ffad-4866-8e4e-6a0ac35130f7.png">
`openssl x509 -inform PEM -in signerCert.pem -noout -text`: My cert is printed
`

Code:
```javascript
const cert = {
        wwdr: '../certificate/AppleWWDRCAG4.pem',
        signCert: '../certificate/signerCert.pem',
        signerKey: '../certificate/signerKey.pem',
        password: '<password here>',
      }
    const passRawData = fs.readFileSync('../model/Generic.pass/pass.json');
    const bizCard = JSON.parse(passRawData);
	const pass = new PKPass({},{
		certificates: {
            wwdr: cert.wwdr,
            signerCert: cert.signerCert,
            signerKey: cert.signerKey,
            signerKeyPassphrase: cert.password,
		},
    }, bizCard);
```

**Comment by alexandercerutti** [comment]
Hey there @hello0827, thanks for using passkit-generator!

I guess the issue here is that you are passing paths as certificates instead of their contents.

[API Documentation](https://github.com/alexandercerutti/passkit-generator/wiki/API-Documentation-Reference#constructor) specifies that you should read your certificates files before generating the Pass.

Let me know!

**Comment by almukhametovd** [comment]
@hello0827 also, possible issue when you have used Buffer was wrong PKPass class creation.
You should put your certificates to class like this:
`const bizCard = JSON.parse(passRawData);
	const pass = new PKPass({},{
            wwdr: cert.wwdr,
            signerCert: cert.signerCert,
            signerKey: cert.signerKey,
            signerKeyPassphrase: cert.password
    }, bizCard);`
    without **certificates** object wrapper

**Comment by alexandercerutti** [comment]
Good catch @almukhametovd!! I completely missed that

**Comment by hello0827** [comment]
> 
@almukhametovd 
Thanks for the response. I tried to read the cert as buffer or string before and it's not working as well. So I tried to pass the path. Sorry for confusion. 

I resolved the issue now. It's the class creation issue. Thank you for your help.
