### ISSUE TITLE
Cannot proceed with pass creation due to bad keys format in overrides.

### ISSUE THREAD

**Issue by midoshawky** [alexandercerutti/passkit-generator#146]
## Running OS

Mac OS Ventura 13.3.1

## Running Node Version

v19.9.0

## Description

im trying to generate the pass from any example but it ended with this message in the response "Cannot proceed with pass creation due to bad keys format in overrides." 
this is some of the error stack  
    
    at Pass._parseSettings (/Users/muhammedshawky/Downloads/passkit-generator-master/src/pass.js:675:10)
    at new Pass (/Users/muhammedshawky/Downloads/passkit-generator-master/src/pass.js:44:28)
    at manageRequest (/Users/muhammedshawky/Downloads/passkit-generator-master/examples/barcode.js:18:13)
    
i tried every thing and made sure about the certificates also

## Expected behavior

it should generate the pkpass normally as every one did :"D

## Steps to reproduce

just the same process of the example 

## Other details

-   [ ] I'm available to open a Pull Request to resolve the problem (after the triage)

**Comment by alexandercerutti** [comment]
Hey there @midoshawky, thanks for using passkit-generator!

Can you please tell me which version of passkit-generator are you using?

Thanks

**Comment by midoshawky** [comment]
Hi @alexandercerutti  thanks for replying Im using the latest   3.1.9

**Comment by alexandercerutti** [comment]
Are you sure, @midoshawky ? I do not recognize that file `pass.js` not `_parseSettings` functions. May that belong to a previous version? I honestly do not remember...

**Comment by alexandercerutti** [comment]
Do you mind sharing some code?

**Comment by midoshawky** [comment]
Yeah sure here is
 
Pass.json
{
  "formatVersion": 1,
  "passTypeIdentifier": "*******",
  "serialNumber": "nmyuxofgna",
  "teamIdentifier": "*******",
  "locations": [
    {
      "longitude": -122.3748889,
      "latitude": 37.6189722
    },
    {
      "longitude": -122.03118,
      "latitude": 37.33182
    }
  ],
  "barcodes": [
    {
      "message": "123456789",
      "format": "PKBarcodeFormatQR",
      "messageEncoding": "iso-8859-1"
    }
  ],
  "barcode": {
    "message": "123456789",
    "format": "PKBarcodeFormatQR",
    "messageEncoding": "iso-8859-1"
  },
  "organizationName": "Bumpy",
  "description": "Apple Event Ticket",
  "foregroundColor": "rgb(255, 255, 255)",
  "backgroundColor": "rgb(60, 65, 76)",
  "eventTicket": {
    "primaryFields": [
      {
        "key": "event",
        "label": "EVENT",
        "value": "The Beat Goes On"
      }
    ],
    "secondaryFields": [
      {
        "key": "loc",
        "label": "LOCATION",
        "value": "Moscone West"
      }
    ]
  }
}


Here is the first lines of barcode.js

app.all(function manageRequest(request, response) {

	let passName = request.params.modelName + "_" + (new Date()).toISOString().split('T')[0].replace(/-/ig, "");

	let pass = new Pass({
		model: `./models/${request.params.modelName}`,
		certificates: {
			wwdr: "./certificates/wwdr_certificate.pem",
			signerCert: "./certificates/signer_certificate.pem",
			signerKey: {
				keyFile: "./certificates/signer_key.pem",
				passphrase: "0123456789"
			}
		},
		
	});
	
if u can tell me what exactly u need me to share too
@alexandercerutti

**Comment by alexandercerutti** [comment]
@midoshawky please note that you don't have to set the paths for certificates but you have to read them first or set their content.

**Comment by midoshawky** [comment]
Sorry @alexandercerutti i didn't get that 
u mean to read the certificate data with some openssl commands and then put it there ? 
can u explain more because i just followed the example instrucations

**Comment by alexandercerutti** [comment]
I mean to use fs module to read the file or to use something like a process.env variable to get their content

**Comment by midoshawky** [comment]
ummm got you 
so the issue is releated to the certificates it self nothing more right ? 

and if i can ask u a favor if u please can generate me a one with nfc enabled i will be so grateful while im just try to figure out how to fix because im just doing that so that i make the nfc enabled because i tried other packages was generating normally but nfc was not suprorted

**Comment by midoshawky** [comment]
okay nvm thanks any way for your efforts @alexandercerutti

**Comment by alexandercerutti** [comment]
Let me know if you are able to solve after changing the way you read the certificates.

**Comment by midoshawky** [comment]
okay sure

**Comment by midoshawky** [comment]
I managed to skip this issue by using the correct way described in the documentation faced some other issues but was able to fix it currently facing something new :") 
so I guess we should close this one now
thanks for your time @alexandercerutti

**Comment by alexandercerutti** [comment]
Great to know @midoshawky!

It would be awesome if you could leave a ⭐️ on the project if you already didn't. They are really important for me.

**Comment by midoshawky** [comment]
@alexandercerutti  sure
