### ISSUE TITLE
Grouping multiple passes

### ISSUE THREAD

**Issue by ewenmic** [alexandercerutti/passkit-generator#149]
Hey @alexandercerutti 

Thanks for the great package! 

I found #9 and wanted to share that it's now possible to group multiple passes together and issue them in a single file. 
https://developer.apple.com/documentation/walletpasses/distributing_and_updating_a_pass#3793284

I don't know if you'd consider this an in-scope feature request, but if anyone needs similar functionality it's pretty easy to implement. 

I'm generating an array with pass buffers using passkit-generator, then writing them to tmp storage, zipping them up using zip-a-folder, then uploading to google cloud storage with the vnd.apple.pkpasses MIME type.

If it helps anybody here's some code:
https://gist.github.com/ewenmic/dc6e596529ba288c0126e6296c5380d8

**Comment by alexandercerutti** [comment]
Hey @ewenmic, thanks for using passkit-generator!

Actually, .pkpasses are already supported, if you look in the documentation!

I rewrote this library two years ago to support both .pkpass and .pkpasses. I also have an example of generating PKPasses among self-hosted examples in the repository.

Sadly, it looks like .pkpasses are supported only by Safari (maybe Mail?) but not other browsers (like Chrome, even if it is Safari underneath) or other applications, so they are kinda useless to me.

**Comment by ewenmic** [comment]
Thanks for the speedy reply!

I wish I had checked your documentation better the first time - PKPasses looks much more elegant than my workaround. 

Thanks for the note about pkpasses support!
