### ISSUE TITLE
Error on regex of type /(\$.[^ \n]*)/ in changeMessage field

### ISSUE THREAD

**Issue by alexander-san** [alexandercerutti/passkit-generator#15]
I have a pass the respects the schema outlined on the Apple Developer website and which I can successfully create with` ./signpass -p <file>` and also successfully verify with `./signpass -v <file>`

Yet still when I try to generate this pass after following all the steps in the README I get this error when I try to generate the pass.

```
Error: Validation of pass type failed. Pass file is not a valid buffer or (more probabily) does not respect the schema. Refer to https://apple.co/2Nvshvn to build a correct pass.
    at readFile.then.passStructBuffer (~/node_modules/passkit-generator/src/pass.js:135:15)
```

This even happens with some of the Sample passes from the Apple website (Tutorial), e.g. the BoardingPass.pass.

I tried looking into the code but I can not determine at which step or part of the JSON file it fails and also the error message is not very specific. Is there any chance you know where this comes from or how I could fix this or determine where the error comes from?

**Comment by alexandercerutti** [comment]
Hi @alexander-san!
Let's find out! If the pass gives you that error, is because [_validateType](https://github.com/alexandercerutti/passkit-generator/blob/master/src/pass.js#L510) failed, and it can fail for two reasons:

1) there is no key called like one of these: `["boardingPass", "eventTicket", "coupon", "generic", "storeCard"]`

2) Schema validation really fails because you inserted a key not in the [schema](https://github.com/alexandercerutti/passkit-generator/blob/master/src/schema.js#L81)

Each field is an array of [`field`](https://github.com/alexandercerutti/passkit-generator/blob/master/src/schema.js#L40).

You can check if your fields are compliant with the schema.
Anyway, have you tried to start your node process with `DEBUG=*` before? If it is a schema problem, it will give you more details.
Let me know!

**Comment by alexander-san** [comment]
Hi @alexandercerutti 

Thank you for that rapid response.
So I have a pass of "generic" key type.

A truncated version w/o sensitive parts of the .json looks as follows
```
{	
	"description": "$DESCRIPTION",
	"formatVersion": 1,
	"organizationName": "Company Name",
	"passTypeIdentifier": "pass.com.company.id",
	"serialNumber": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"teamIdentifier": "XXXXXXXXXX",
	"voided": false,
	"userInfo": {<truncated>},
	"generic": {
		"primaryFields": [{<truncated>}],
		"auxiliaryFields": [{<truncated>}, {<truncated>}],
		"secondaryFields": [{<truncated>}],
		"backFields": [{<truncated>}]
	},
	"barcodes": [{<truncated>}],
	"expirationDate": "2020-06-30T00:00-00:00",
	"backgroundColor": "rgb(140,100,130)",
	"foregroundColor": "rgb(255,255,255)",
	"labelColor": "rgb(180,180,180)"
}
```
Is there anything obvious I am doing wrong (e.g. barcodes vs. barcode)

As I mentioned with the signpass program from Apple I can perfectly fine generate a functioning pass.

Also I am not too familiar with node so I don't know how to pass the `DEBUG=*` flag - if I put it at the end e.g `node <filename>.js DEBUG=*` I don't get more output.

Thank you for your help.

And for the sample passes I am referring to those passes published [here](https://developer.apple.com/services-account/download?path=/iOS/Wallet_Support_Materials/WalletCompanionFiles.zip)
I attached them here again: Coupon is working for me, but BoardingPass for instance give above described error (after you fix a JSON error at line 75 (one comma too much, oh Apple))

[SamplePasses.zip](https://github.com/alexandercerutti/passkit-generator/files/3054340/SamplePasses.zip)

**Comment by alexandercerutti** [comment]
`barcode` vs `barcodes` is not a problem, as `barcode` is used for backward compatibility (< iOS 8 if I remember correctly);

Of course you can with `signpass`: Apple created it ehehe They cannot provide a test utility that doesn't work. 😄

Start with `DEBUG=*` before all: `DEBUG=* node <filename>.js`.

This evening I'll check the one you linked me. Thank you.

**Comment by alexander-san** [comment]
Awesome thank you.

One last question: In the generate Promise, what would be the easiest way to just save the .pkpass to the disk?

**Comment by alexandercerutti** [comment]
You solved? Which was the problem in case?

If I remember it correctly, you can `.pipe` the resulting Stream to a [`fs.createWriteStream()`](https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options) like below:

```javascript
pass.generate().pipe(fs.createWriteStream(...));
```

As `.generate()` returns a PassThrough Stream, which is both for reading and writing.
The process is the same if you want to pipe the stream to an HTTP Response Object.
Given what I said right above, look at this: [.pipe()](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options).

**Comment by alexander-san** [comment]
```
"generic": {
		"primaryFields": [{
			"key": "member",
			"label": "$MEMBER",
			"value": "FirstName LastName",
			"changeMessage": "$/%@/"
		}], <truncated>

```

I think I found the error. Previously I had "$MEMBER_CHANGED" and the I got the debug message 
` Schema validation failed due to error: child "primaryFields" fails because ["primaryFields" at position 0 fails because [child "changeMessage" fails because ["changeMessage" with value "$MEMBER_CHANGED" fails to match the required pattern: /%@/]]] +0ms
`
But now I reference the wrong localized strings from pass.strings

I found following resource:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html

So I guess I just reference them by index `/2%@/` (e.g. for the 3rd string)?

**Comment by alexandercerutti** [comment]
So initially the problem was that %@ was missing in the string (it is required right now).
About the strings, I never seen that format but I'm understanding what you are trying to do...

**Comment by alexander-san** [comment]
So the problem I was experiencing was with the changeMessage:
I was trying to reference a variable from the localized string from the .lproj folders.
In there for each language we have the pass.strings file with the name to reference and the translation:
`"MEMBER_CHANGED" = "Member name changed to %@.";`

But now when in the .json file I am trying to reference the localized string `MEMBER_CHANGED` it fails by saying I should use `/%@/` which is problematic since I have several localized strings.

So how do I reference these localized strings correctly in my mian json file?

**Comment by alexandercerutti** [comment]
This might be a problem actually. I added a regex to `changeMessage` schema because it is needed to let a pass change to be notified. Maybe I should remove it... or do you think there might be another solution to this? Sadly Apple does not say like "if you start a string with $, it is considered as a placeholder", so I cannot check it: I should force users to insert it, like I do with .pass extension for models. I don't think I can create something like in the link you provided me to be used.

**Comment by alexandercerutti** [comment]
So you are saying to put a regex like `/(\$[a-zA-Z0-9]+|%@)/`?

**Comment by alexander-san** [comment]
more like this as regex: `/(\$[a-zA-Z][a-zA-Z0-9\_]*|%@)/`
or if you want to simplify it yet still it should contain the underscore
`/(\$[a-zA-Z0-9\_]+|%@)/`

or what would be the most logic yet also restrictive `/(\$[A-Z][A-Z0-9\_]*[?=\s]|%@)/` 

Because a placeholder - like variables - should not start with a number and since it is a "constant" be in all CAPS which would also be a strong protection against unwanted escapings.
Since it is all CAPS we have to allow for underscores for better readability.
Also I added a positive lookahead for a whitespace as it is weird and unintuitive to partially escape in this case.

What do you think?

**Comment by alexandercerutti** [comment]
This is great and I agree with you about the last one but it is not clear to me yet why the positive lookahead.

**Comment by alexander-san** [comment]
@alexandercerutti I would propose that because it would be weird to have a regex like this:
Imagine following scenario:
pass.strings:
`"$MEMBER" = " Alexander";`

pass.json
```
...
"changeMessage": "$MEMBERforver"
...
```
would be replaced as `Alexanderforever`

Therefore, I suggest we are restrictive and require a whitespace to separate the placeholder from the rest of the text.

**Comment by alexandercerutti** [comment]
I think that here the doubt is legit: can placeholders be used only for part of the string?? I was thinking that the placeholders were replacing the whole strings...

**Comment by alexander-san** [comment]
Exactly this is why we have to add the [?=\s] part.
I was playing with that [awesome website](regexr.com) and that is how I discovered that if we don't add this we can have a part of a string also be a placeholder which should not be the case ...

**Comment by alexandercerutti** [comment]
I just tried to mix a Placeholder with part of the string (in the description, but one localizable string is good as another) and you cannot mix them:
If you do `"$MEMBER" = "Alexander"` and then in the localizable string you set as value `"Member name is $MEMBER"`, `$MEMBER` will be printed out literally and not parsed.

Therefore the positive lookahead if not needed.

**Comment by alexander-san** [comment]
1) okay maybe I misunderstood then
2) I used * because I say the first one has to be either a-z or A-Z and then there can be 0 or more of a-z or A-Z or 0-9 (that is why it changes from + to *) -> this simply disallows a placeholder to start with a number.
3) what are you referring to with "all placeholders" - I am not sure if I understand correctly

**Comment by alexandercerutti** [comment]
The quantifier * is valid only for the "group" (or the selector) right before. So if you have `/(\$[A-Z][A-Z0-9\_]*|%@)/`, * will be applied only to [A-Z0-9], not to [A-Z]. That's why I'm asking you.

About the second part, I mean the placeholders pushed through `.localize` method and in pass.json.

**Comment by alexander-san** [comment]
Exactly so the [A-Z] is the exactly one and the [A-Z0-9]* part is 0 or more which combined together gives the original 1 or more what we want.

Second part I am still not sure what your plans are sorry.

**Comment by alexandercerutti** [comment]
Oh okay, now I got it. You are right.

I mean, for the second part, my doubt is: shouldn't we uniform the way the package let to add placeholders? Like all with $ or none?

**Comment by alexander-san** [comment]
Yes in the pass.strings all placeholder/variables should start with a `$` sign.
Totally!

**Comment by alexandercerutti** [comment]
And going back to the problem above: how should we do that?

> This might be a little problem, as we cannot force in no ways to insert $ before the string as the content might not be a placeholder.

**Comment by alexander-san** [comment]
We could parse the pass. strings to check that ever newline starts with `"$` or ignore when (`#` or `//` or empty) and stop parsing if this is not the case. Then simply output a descriptive warning like
in `There was a problem parsing the the localized strings in .lproj pass.strings. Please make sure that they follow the correct scheme outlined under developer.apple.com/somewhere`

**Comment by alexandercerutti** [comment]
I do not execute any parsing process right now except for pass.json to get its static information.
I was thinking about the dynamic strings, the ones that will be pushed inside the generated pass.strings

**Comment by alexander-san** [comment]
Here a Swiss boarding pass for instance

```
"description" = "SWISS Boarding pass";
"relevantText" = "LX1577 Boarding 10:30";
"seatHeading" = "Seat";
"seatchangeMessage" = "Seat number changed to %@";
"gateHeading" = "Gate";
"gatechangeMessage" = "Gate changed to %@.";
"departsHeading" = "Departure";
"departchangeMessage" = "Departure airport changed to %@.";
"destinationHeading" = "Arrival";
"destinationchangeMessage" = "Destination airport changed to %@.";
"passengerHeading" = "Passenger";
"passengerchangeMessage" = "Passenger changed to %@.";
"stateHeading" = "Status";
"statechangeMessage" = "Status number changed to %@";
"flightHeading" = "Flight";
"flightchangeMessage" = "Flight number changed to %@";
"dateHeading" = "Date";
"datechangeMessage" = "Date number changed to %@";
"boardingHeading" = "Boarding";
"boardingchangeMessage" = "Boarding number changed to %@";
"classHeading" = "Class";
"classchangeMessage" = "Class number changed to %@";
"eTicketHeading" = "Your ticket number:";
"backField" = "Status


Travel class
xxxxxxxxx

Ticket number
xxxxxx

Reservation number
xxxxx

Check-in sequence
4

Checked-in baggage
See E-Ticket terms and conditions for detailed baggage allowance. Additional baggage allowance may apply for Frequent Flyers or if purchased separately.

Hand baggage
1 piece
Maximum weight per piece:8 kg
Maximum size: 55 x 40 x 23 cm
(width x depth x height)

Dangerous goods
No dangerous goods are allowed in either checked in baggage or carry-on-baggage.
More information:
<a href='https://swiss.com/dangerousgoods'>swiss.com/dangerousgoods</a>

Baggage drop-off
Your flight departs from terminal 3. Please report with your baggage to the Check-in counter.
Kindly consult our website for the latest baggage drop-off/check-in times of your departure airport:
<a href='https://www.swiss.com/ch/EN/prepare/check-in/checkin-times'>swiss.com/latest_checkin</a>

Boarding time
Please be at your departure gate at the boarding time stated. Otherwise your seat may be re-assigned. All times are local times.

Change of seat reservation/cancellation
To change your seat reservation or to cancel your flight please log in to our web site:\r<a href='https://checkin.swiss.com/ck.fly?locale=EN&first_name1=LEO&last_name1=MION&departure_port=VIE&departure_date=2018/08/20&flight_number=1577&carrier=LX&group=Yes&etkt=7242310259092&source=acirework'>swiss.com</a>

SWISS wishes you a pleasant flight.";
```

and the corresponding pass.json file:

```
"boardingPass": {
      "transitType": "PKTransitTypeAir",
      "auxiliaryFields": [
         {
            "key": "flightHeading",
            "value": "LX1577",
            "label": "flightHeading"
         },
         {
            "key": "dateHeading",
            "value": "20 Aug 2018",
            "label": "dateHeading"
         },
         {
            "key": "boardingHeading",
            "value": "10:30",
            "label": "boardingHeading"
         },
         {
            "key": "classHeading",
            "value": "Economy",
            "label": "classHeading"
         }
      ],
      "backFields": [
         {
            "key": "backFieldKey",
            "value": "backField"
         }
      ],
      "headerFields": [
         {
            "key": "seatHeading",
            "value": "6A",
            "label": "seatHeading"
         },
         {
            "key": "gateHeading",
            "value": "N/A",
            "label": "gateHeading"
         }
      ],
      "primaryFields": [
         {
            "key": "departsHeading",
            "value": "VIE",
            "label": "departsHeading"
         },
         {
            "key": "destinationHeading",
            "value": "ZRH",
            "label": "destinationHeading"
         }
      ],
      "secondaryFields": [
         {
            "key": "passengerHeading",
            "value": "MION/LEO",
            "label": "passengerHeading"
         },
         {
            "key": "stateHeading",
            "value": "LH*S HON",
            "label": "stateHeading"
         }
      ]
   }
```

**Comment by alexander-san** [comment]
So essentially no other way then building a dictionary of names of placeholders when we have a value field, then check for every word that we encounter whether it is in the dictionary: if not we continue otherwise we replace.

This is more tricky then we thought.

**Comment by alexandercerutti** [comment]
I agree, it is very tricky. And I don't know if it might be time-spending worth to work on this. Maybe for the v2, as I was planning to improve the parsing process for the fields in pass.json (static ones).

Even not talking about the pre-existing pass.strings, this is tricky because we might force the devs to use or all placeholders or all not placeholders.

I think that for the sake of the uniformity, we might just remove %@ right now as a regex and use this for the future. What do you think?

**Comment by alexander-san** [comment]
Why not just pass the key value of the field that has a changeMessage along when replacing and if we encounter a `%@` then we replace it with the value of the field.

This would be a great and not at all complicated workaround until we change the parser in v2

**Comment by alexandercerutti** [comment]
Well, that should Wallet's task... I don't know...

**Comment by alexandercerutti** [comment]
I came up with this solution. Right now, I can remove this check from the model/schema. Future checks 
and restrictions will be implemented within the new major version, as the discussed changes might be considered as breaking changes.

So, at the moment, I'm going to close this issue topic but I'll probably resume it once v2.0.0 development will begin (if needed).

Thank you very much for the collaboration, @alexander-san.
