### ISSUE TITLE
Generating certificate wiki might need updaing

### ISSUE THREAD

**Issue by fabiancook** [alexandercerutti/passkit-generator#154]
## Running OS

macOS Ventura 13.4.1

## Running ~~Node~~ openssl Version

```
openssl version -a                                                                            
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
built on: Tue May 30 12:13:24 2023 UTC
platform: darwin64-arm64-cc
options:  bn(64,64)
compiler: clang -fPIC -arch arm64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/opt/homebrew/etc/openssl@3"
ENGINESDIR: "/opt/homebrew/Cellar/openssl@3/3.1.1_1/lib/engines-3"
MODULESDIR: "/opt/homebrew/Cellar/openssl@3/3.1.1_1/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_armcap=0x187d
```

## Description

Using the instructions provided here: https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates 

On macOS Ventura you get back the output:

```
Error outputting keys and certificates
005E04F401000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

## Expected behavior

For the `.pem` file to be created as per the steps

## Steps to reproduce

Running:

```bash
openssl pkcs12 -in pass.p12 -clcerts -nokeys -out signerCert.pem
```

## Updated steps:

```bash
 openssl pkcs12 -in pass.p12 -clcerts -nokeys -out signerCert.pem -legacy
 ```
 
 [Source](https://stackoverflow.com/a/72859712/1174869)
 
The `.pem` exports after using `-legacy` 
 
## Other info:

-   [ ] I'm available to open a Pull Request to resolve the problem (after the triage)

 
 Hope this helps anyone else running into this!

**Comment by alexandercerutti** [comment]
Hi @fabiancook, thank you very much for your issue! It is very precious for passkit-generator.

So, if I understand correctly, some tools are still generating the P12 in a "legacy mode" (RC2-40-CBC) and newer OpenSSL versions might, therefore, require the `-legacy` flag to parse them correctly.

That's fine, but there are still a few things that are not yet clear to me and that I'd like to ask you (if you have any clue) so we can document it better on wiki:

1) Were you using MacOS Ventura to generate the PKCS#12 file, or were you following the "terminal steps"?

2) If the answer to question one is "terminal", what happens if you generate it with Ventura?

3) Do you perhaps have any idea on how could we identify which kind of algorithm has been used on PKCS#12? So we can indicate whether one should add the legacy flag.

Thank you!

**Comment by fabiancook** [comment]
I was using the "Keychain Access" on macOS Ventura application to generate the p12 file 

... I can say that I have fully integrated since posting this issue and am able to generate passes perfectly! 

<details><summary>Generated Pass</summary>
<p>

![image](https://github.com/alexandercerutti/passkit-generator/assets/4337080/5f777f02-3917-414b-ae92-6051780bf215)

</p>
</details>

**Comment by alexandercerutti** [comment]
Sorry @fabiancook but I didn't quite get what you mean by "I can say that I have fully integrated since posting this".

**Comment by alexandercerutti** [comment]
I will make some attempts later if you are not able to do them.

**Comment by alexandercerutti** [comment]
@fabiancook you are right, I forgot steps through terminal do not involve P12 creation 😅

So what we are saying is that Keychain Access on Ventura is not yet updated to work through the new algorithm, isn't it?

**Comment by fabiancook** [comment]
Correct. 

Going through the Keychain Access process on Ventura, and exporting the p12 key of the private key + certificate together, from Keychain Access, requires the use of `-legacy` when creating the `.pem` files based on the `.p12` file exported.

**Comment by alexandercerutti** [comment]
Okay, I've tried to install OpenSSL 3.1.2 and attempted to pack a P12.
This is a comparison between a PKCS12 I obtained in the previous months (but also one that I tried to generate through LibreSSL) and a new one I tried to create through my `signerCert.pem` and my `signerKey.pem`.

<img width="720" alt="immagine" src="https://github.com/alexandercerutti/passkit-generator/assets/5442545/83cc771a-bf17-4e8f-9bcd-8ecc0d7bfbb2">

So I guess we could write in the wiki that:

1) To check the OpenSSL / LibreSSL version. OpenSSL >v3.0.0 added this change in 2021 ([version's changelog](https://github.com/openssl/openssl/blob/master/CHANGES.md#changes-between-111-and-300-7-sep-2021)) while LibreSSL didn't (yet?) ([changelog](https://github.com/libressl/portable/blob/master/ChangeLog))
2) Add `-legacy` if using an OpenSSL > v3.0.0 and if the p12 generated is encrypted through `RC2-CBC`

What do you think?

**Comment by alexandercerutti** [comment]
I've updated the wiki! Let me know what you think of it!
Here, on step 7, I've added a link to a whole new paragraph: https://github.com/alexandercerutti/passkit-generator/wiki/Generating-Certificates#generate-certificates-through-macos
