### ISSUE TITLE
NodeJS newbie: Can't get the Pass to be generated

### ISSUE THREAD

**Issue by dwinc** [alexandercerutti/passkit-generator#16]
Sorry for leaving a comment in the issue section, but I am not sure how to reach out otherwise. 
I am new to NodeJS, but felt like this could be the best/easiest way to setup a web service for generating a Passbook Pass for an iOS (built in ionic) app that I work on. 
I also apologise for the basic questions. I am not very good with this (yet).

I followed your documentation and all seems well. Got the certificates etc. sorted.
When I run your "usage example" straight out of the box (with of course my certificates and passphrase set), I get the error from node: pass is not defined. 
I see that you define "let examplePass", but then run "pass.generate()".
Should it not be "let pass = new Pass({ ..." ?

When I change it to "let pass = new Pass " it does run, but I am not sure it actually generates anything. 
I am testing it locally atm.

Since I am completely new to NodeJS (but having Javascript experience) I am not entirely sure how to run this module correctly so that it generates a pass that I can open from the app.

I am not too worried about the look/feel of the pass yet. Just wanted to test if this works.
Hope you can help a little! 

Appreciate the effort you put into developing this module! By far the best documented version I found so far. 
Cheers!

**Comment by alexandercerutti** [comment]
Hi @dwinc, don't worry, you'll learn!
Thank you! I've built the docs with this goal behind: giving others as much as possible of what I learnt about the topic. 😄

Wait a moment: I import Pass as an object via [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). Then create a `new Pass()`, assigning it to `examplePass` variable.

___

The concept behind this library is the following one: this library will only provide you all the tools to generate one, not to send one. If you look in the [examples folder](https://github.com/alexandercerutti/passkit-generator/tree/master/examples), you can see there's a webserver.js created with Express.JS that I use as base for every example.
The webserver opens the port 8080 for localhost so when you'll contact the address `localhost:8080/gen/examplePass` (or whatever, it depends by the example, in one of them I forced the example name to be specific one), you'll receive a pass as .pkpass (which is a zip file).
If you open the address on a Apple Wallet-compatible device (may also be an Android with specific apps) on the browser, the app (like Wallet) will be called automatically.

What you need to learn first of all, is the usage of Streams, as `.generate()` will return a specific type of Stream, called [`PassThrough`](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) Stream, which is a data stream used for both reading it and writing it.
So, using that, you can create for example a Writing Stream and pipe the result into it like

```javascript
...
pass.generate().pipe(fs.createWriteStream(...));
...
```
or send it (like reading) to an HTTP Response Object (like in the examples):

```javascript
...
pass.generate().pipe(response);
...
```

If you have other questions, don't hesitate!

**Comment by alexandercerutti** [comment]
Whops, @dwinc I'm sorry! You are right! I looked at it a lot of times and never noticed the error. I'm going to correct it, thank you.

**Comment by dwinc** [comment]
:) @alexandercerutti Glad that I spotted that correctly. 
Thanks for replying so fast! I indeed lack the experience with streams. Let me look into that first before I ask any more questions. 
Cheers! 
Ps. will let you know when I am successful and when your solution has been implemented in the app (for a big organisation!)

**Comment by alexandercerutti** [comment]
Perfect, you are welcome. 😄 I'm waiting for news from you!

**Comment by dwinc** [comment]
Hey I found your examples and got those to work! Perfect thank you. 
2 little comments:
- Example instructions could include "cd passkit-generator" after git clone, and to install express I would suggest "npm install express --save" because your line did not work for me.
- Your webserver.js has "app.listen(8080, "0.0.0.0",...) where your example instructions says: localhost:3000, I suppose you might as well change that to 3000, "127.0.0.1" 

Will play around with the passes now! Thanks again!
