### ISSUE TITLE
Pass could not be opened

### ISSUE THREAD

**Issue by axlic** [alexandercerutti/passkit-generator#166]
## Running OS

Current
## Running Node Version
NODE 18 LTS

## Description

pk pass is generating successfully but when I try to open it, Pass could not be opened error occurred
<img width="361" alt="Screenshot 2023-09-27 at 5 51 48 PM" src="https://github.com/alexandercerutti/passkit-generator/assets/143682505/87adcbcb-43b8-4f2d-a084-da3d178d49f8">

## Code

```javascript
const express = require('express');
const { PKPass } = require("passkit-generator");
const fs = require("fs");
const path = require("path");

const wwdr = fs.readFileSync(path.resolve(__dirname, "./wwdr.pem"));
const signerCert = fs.readFileSync(path.resolve(__dirname, "./cert.pem"));
const signerKey = fs.readFileSync(path.resolve(__dirname, "./key.pem"));

const app = express();
const port = 3000;

app.get('/', (req, res) => {
    res.json({"test":'Hello World!'});
});

app.get('/pass', async (req, res) => {
    try{
        const pass = await PKPass.from({
            /**
             * Note: .pass extension is enforced when reading a
             * model from FS, even if not specified here below
             */
            model: "./model/DBC.pass",
            certificates: {
                wwdr,
                signerCert,
                signerKey,
                signerKeyPassphrase: '1234'
            },
        }, {
            // keys to be added or overridden
            serialNumber: "AAGH44625236dddaffbda",
            teamIdentifier: "myTeamID",
            webServiceURL: "https://example.com/passes/",
            authenticationToken: "vxwxd7J8AlNNFPS8k0a0FfUFtq0ewzFdc",
            description: "Demo pass",
        });

        pass.primaryFields.push({
            key: "name",
            label: "Name",
            value: "Jon Doe",
        })

        pass.secondaryFields.push({
            key: "bank",
            label: "Bank",
            value: "UBL",
        })

        pass.auxiliaryFields.push({
            key: "balance",
            label: "Balance",
            value: "$10",
        })

        const buffer = pass.getAsBuffer();
        // storage to local file
        fs.writeFileSync("myFirstPass.pkpass", buffer);
        console.log("Pass created successfully");

        res.send('created.')
    }
    catch (error) {
        console.error('Error creating pass:', error);
        res.status(500).send('An error occurred while creating the pass.');
    }
});



app.listen(port, () => {
    console.log(`Server is listening at http://localhost:${port}`);
});
```

DBC.pass structure 

<img width="285" alt="Screenshot 2023-09-27 at 5 55 06 PM" src="https://github.com/alexandercerutti/passkit-generator/assets/143682505/61402baf-ed37-4796-af56-a6896e10ad98">

# Pass.json

```json
{
	"formatVersion" : 1,
	"passTypeIdentifier" : "pass.com.mycompany.app",
	"teamIdentifier" : "myTeamID",
	"serialNumber" : "12345",
	"barcode" : {
		"message" : "https://downloads.timoliver.com.au/tim-businesscard.pkpass",
		"format" : "PKBarcodeFormatQR",
		"messageEncoding" : "iso-8859-1"
	},
	"organizationName" : "Skyive",
	"description" : "SkyiveBusinessCard",
	"foregroundColor" : "rgb(255, 255, 255)",
	"backgroundColor" : "rgb(20, 20, 20)",
	"labelColor" : "rgb(190, 57, 57)",
	"generic": {
		"primaryFields":[],
		"secondaryFields":[],
		"auxiliaryFields":[]
	}
}

```

**Comment by alexandercerutti** [comment]
Hi @axlic, thanks for using passkit-generator!

I don't see anything wrong in your code after a first look.
Could you please look at the guide for troubleshooting in the wiki and check if Console.app tells you more information?

https://github.com/alexandercerutti/passkit-generator/wiki/Troubleshooting-(Self-help)#through-console-mac-only

Console.app might give a hint to you where you should look at.

Let me know!

**Comment by axlic** [comment]
@alexandercerutti  in the console I'm seeing this error

Invalid data error reading pass pass.com.company.app/AAGH44625236dddaffbda. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.

**Comment by axlic** [comment]
I've checked the certificate the team id and passTypeId is correct


<img width="932" alt="Screenshot 2023-09-27 at 8 18 05 PM" src="https://github.com/alexandercerutti/passkit-generator/assets/143682505/809c9651-20ab-4636-8376-1aa19eb126a0">

**Comment by alexandercerutti** [comment]
@axlic if you can confirm the values are fine, I don't have any other clue honestly

**Comment by axlic** [comment]
@alexandercerutti 
currently I'm using macOS 13.4.1 (c) 
is is make any problem ?

**Comment by alexandercerutti** [comment]
It shouldn't. I'm running on the same OS (Ventura) and I have no issues.
I still think there might be some unknown (yet) issues with the certificates.

If you are available to send them to me in private (on telegram) I can make some tests and compare them with mine.

**Comment by axlic** [comment]
give me telegram id

one thing more.. is it make difference using G1, G2 or G5 wwdr certificate?

**Comment by alexandercerutti** [comment]
You can find it on my Github profile.

There are differences. Not actually sure which ones (except for G1, which is expired).
You should use G4, as also reported in the screenshot you sent me.

**Comment by axlic** [comment]
@alexandercerutti please check telegram

**Comment by axlic** [comment]
Thank you @alexandercerutti  for creating Awesome package like this, it made my day.

**Comment by axlic** [comment]
Thank you @alexandercerutti for creating Awesome package like this, it made my day.

**Comment by alexandercerutti** [comment]
Glad you solved @axlic ! I will still perform some investigations this evening to check what happened.

It would be awesome if you could leave a ⭐ on the project!
