### ISSUE TITLE
Help with relevantDate for notification

### ISSUE THREAD

**Issue by Gangadhar9848** [alexandercerutti/passkit-generator#168]
##macOS Venture 13.5.2

nodejs: v18.18.0

## Description

Hi @alexandercerutti 

Can you please help with me on 'relevantDate' attribute which will notify in the mobile? I tried giving multiple formats but unable to get notified. we should be giving iso format, so I gave this

 "labelColor" : "rgb(0, 0, 0)",
  "serialNumber" : "888",
  "relevantText" : "Notify MESSAGE",  
  "relevantDate" : "2023-09-28T16:45:00+02:00", (To test in live in UTC+2)

Would it get notified before 1-2 hour or just at the point of time given?. Please help me if i made some mistake

## Expected behavior

Based on the relevantdate attribute, wallet pass should be notified	

## Steps to reproduce

Give ISO formatted value to relevantDate attribute in pass.json

## Were you able to verify it by using (and changing) the examples?

YES, WITH MULTIPLE DATE FORMATS

## Other details

-   [ ] I'm available to open a Pull Request to resolve the problem (after the triage)

**Comment by alexandercerutti** [comment]
Hi @Gangadhar9848, there are not very much info available about the relevancy date.

We discussed it here. You can give it a read and come back if you need something more: https://github.com/alexandercerutti/passkit-generator/discussions/141

Let me know!

**Comment by Gangadhar9848** [comment]
Thanks @alexandercerutti , I went through all these and was unable to crack it. 

I tried giving 
  
"relevantDate" : "2023-09-28T17:45:00+02:00", this way and in zip file(pkpass to zip) it converted to "relevantDate":"2023-09-28T15:45:00.000Z". which i believe is correct. please correct me if I am wrong. but unable to notify in the device. i tried giving 1 hour before, 2 hours before and 3 hour before.

**Comment by alexandercerutti** [comment]
Do you have notifications enabled for Apple Wallet?

**Comment by Gangadhar9848** [comment]
yes for every pass i verified

**Comment by alexandercerutti** [comment]
What kind of pass are you generating? Does it support `relevantDate`? I'm referring to the table linked in the discussion.

**Comment by Gangadhar9848** [comment]
Yes @alexandercerutti i saw the table from apple as well. i did generic

**Comment by alexandercerutti** [comment]
I honestly don't know from what it does depend from. [The new Apple Developer documentation](https://developer.apple.com/documentation/walletpasses/pass/showing_a_pass_on_the_lock_screen) does not provide anything useful to this as well.

**Comment by alexandercerutti** [comment]
I honestly don't know from what it does depend from. [The new Apple Developer documentation](https://developer.apple.com/documentation/walletpasses/pass/showing_a_pass_on_the_lock_screen) does not provide anything useful to this as well.

Maybe by looking at Console.app logs, you might be able to retrieve some more information.

**Comment by Gangadhar9848** [comment]
@alexandercerutti i did couple of tests and found out that its not working for generic type pass, with the whole JSON i just changed the type to event ticket and did work. Apple table says it should work for generic as well. any thoughts?

**Comment by alexandercerutti** [comment]
None, sorry.

**Comment by Gangadhar9848** [comment]
@alexandercerutti For now I stick to eventticket type, Generic is something not working out. will update if i find any. you can close meanwhile
