### ISSUE TITLE
The pass “XYZ” could not be opened. - how to debug?

### ISSUE THREAD

**Issue by Arsenalist** [alexandercerutti/passkit-generator#170]
Monterey 12.4 M1 , passkiet 3.1.11

I followed the steps and was able to successfully generate a .pkpass file, but whenever I try to open it anywhere I get:

`The pass “Jump Comedy Tickets.pkpass” could not be opened.`

I tried in Safari/Mac, Safari/iPhone, terminal on Mac, but it's all the same. I just don't know how to debug this.

Here is the model file:

```
{
  "description": "Comedy Tickets from Jump Comedy",
  "organizationName": "Jump Comedy",
  "passTypeIdentifier": "pass.com.jumpcomedy.tickets",
  "teamIdentifier": "com.jumpcomedy",
  "logoText": "Jump Comedy",
  "formatVersion": 1,
  "eventTicket": {}
}
```

The only other files in the folder are just images:
```
.
├── background.png
├── icon.png
├── logo.png
├── pass.json
└── thumbnail.png

1 directory, 5 files
```

I verified that the `passTypeIdentifier` matches what I have configured in the developer account, here is the code which generates the "Jump Comedy Tickets.pkpass" file:

```
        const { wwdr, signerCert, signerKey, signerKeyPassphrase } = getCertificatesContentsSomehow();
        const pass = await PKPass.from({
            model: path.join(__dirname, '/../vendors/apple/Jump Comedy Tickets.pass'),
            certificates: {
                wwdr,
                signerCert,
                signerKey,
                signerKeyPassphrase
            },
        }, {
            // keys to be added or overridden
            serialNumber: "AAGH44625236dddaffbda"
        });
        pass.setBarcodes("36478105430"); // Random value
        const buffer = await pass.getAsBuffer()
        fs.writeFileSync(path.join(__dirname, '/Jump Comedy Tickets.pkpass'), Buffer.from(buffer).toString())
```        

I think the certificates etc. are fine as otherwise the file would not have been generated

I'm kind of lost on how to debug this further.

**Comment by alexandercerutti** [comment]
Ho @Arsenalist, thanks for using passkit-generator!

Did you try the guide in the wiki for debugging through Console.app? It might help you to understand the error message.

Let me know!

**Comment by Arsenalist** [comment]
Thank you for the response. I just tried that, and it has two things in it. Before I go into Googling this, anything jump at you?
 
```
PKZipArchiver: archive_read_next_header failed - Extra data overflow: Need 20669 bytes but only found 9 bytes.

ERROR: Error Domain=PKPassKitErrorDomain Code=1 "The pass cannot be read because it isn’t valid." UserInfo={NSLocalizedDescription=The pass cannot be read because it isn’t valid., NSUnderlyingError=0x600000f166a0 {Error Domain=PKPassKitErrorDomain Code=1 "(null)"}}
```

**Comment by alexandercerutti** [comment]
Try to avoid writing it to the file system and instead serve it directly. You are now the first having such problem, but I'm not sure why. Of course there is no description on the web because is an internal Apple library. Maybe on some Russian or Chinese forum you can fine something, but I don't know nothing else.

Let me know

**Comment by Arsenalist** [comment]
Thank you. Just one last question. Is it ok to assume that certificates/keys are not an issue since the file was successfully generated?

**Comment by alexandercerutti** [comment]
No, but a different error message should appear. This is exclusively about compression and zip format.

P.s. I'm not so sure your teamIdentifier will be recognized as correct. I don't know if Apple performs any kind of validation on it or just against the signature.

**Comment by Arsenalist** [comment]
Thank you. The team name was definitely wrong but generating it dynamically instead of file system worked! Thank you.

**Comment by alexandercerutti** [comment]
Great! Glad it solved!

If you could leave a ⭐️ on the project, that would be awesome!
