### ISSUE TITLE
Deploy serverless to AWS Lambda but can not work.

### ISSUE THREAD

**Issue by JoeyYang2010** [alexandercerutti/passkit-generator#176]
Hi there:
I tried to deploy serverless on lambda but can not work,I am not sure what I am done is wrong.
![image](https://github.com/alexandercerutti/passkit-generator/assets/73459721/15b8c7db-7957-4e3d-9114-739282101e6e)
![image](https://github.com/alexandercerutti/passkit-generator/assets/73459721/d17d1918-31a5-44e3-8680-be4057859e78)

**Comment by alexandercerutti** [comment]
Hi @JoeyYang2010, thanks for using passkit-generator!

I don't know what your code is, so I don't think I can help you like this.
Also, I'm not very much into Lambdas, so I will try to help you as I can.

**Comment by JoeyYang2010** [comment]
> Hi @JoeyYang2010, thanks for using passkit-generator!
> 
> I don't know what your code is, so I don't think I can help you like this. Also, I'm not very much into Lambdas, so I will try to help you as I can.

I am following passkit-generator-master\examples\serverless\README.md to deploy lambda,but failed.

**Comment by alexandercerutti** [comment]
So you are using it as-is?

Maybe there's something different. I always tested it locally. I'll try to give a look into it as soon as I can if you cannot came up with a solution.

**Comment by alexandercerutti** [comment]
I won't provide a zip file. That's way out of this project scope. I made examples just to show passkit-generator can be used with them.

**Comment by alexandercerutti** [comment]
Hey @JoeyYang2010, have you found the issue or a workaround? I didn't have time to look at it, sorry. If you found the reason is in passkit-generator, do you please tell me so I can fix or could you open a PR? 

Thank you!
Let me know

**Comment by alexandercerutti** [comment]
Closing this as I didn't have time to investigate and apparently this seems to not be a problem anymore.

If someone still has issues, I'll open it again.
