### ISSUE TITLE
Deletion of wallet passes in wallet.

### ISSUE THREAD

**Issue by prashant03Dev** [alexandercerutti/passkit-generator#177]
STEPS PERFORMED:

 -Created pass.
-save buffer to cloud.
-Load url to mobile.
-View the pass.
-When try to add the second pass,it overwrittes or delete the old issued pass.

#Issue:
  -When trying to add the new pass from the same identitifer,it deletes the old pass.
  
  @alexandercerutti I had go through the pass.json file,at there one key name "serialNumber" is there.
  
  how would i set that key while creating pass.Tried to set the key value but it say's there is no property there.

**Comment by alexandercerutti** [comment]
Hey there, I'm glad you already solved it!

For future reference, props in the `PKPass` constructor or `PKPass.from` need to be used to override the `serialNumber`, which must be unique in a device.

Anyway, I suggest you not to save the buffer to the cloud because it is useless to keep such a representation of data. Try to serve it directly to the device instead as the HTTP request completes.

**Comment by prashant03Dev** [comment]
@alexandercerutti thanks,we will use your mentioned steps.

**Comment by prashant03Dev** [comment]
@alexandercerutti We need one more information for syncing or removing the wallet passes,that are already added,Is there any apple developer api for removing the passes or sync the wallet.

Or do we need to maintain at the database level.

**Comment by alexandercerutti** [comment]
Just maintain user device info at the database level. You don't have control over the user's wallet.
I think you will just receive a notification on the server when Apple Wallet will unregister for it. I honestly don't know when this happens, maybe when it is expired or when the user deletes.

You should receive a notification at this endpoint:
https://developer.apple.com/documentation/walletpasses/unregister_a_pass_for_update_notifications

You can follow this for more reference on the whole flow.
https://developer.apple.com/documentation/walletpasses/adding_a_web_service_to_update_passes#3733261

**Comment by prashant03Dev** [comment]
@alexandercerutti thanks,we will review this one,and definately reach you out.

**Comment by prashant03Dev** [comment]
@alexandercerutti Can u suggest me the android wallet passes refrences for pass creation?

**Comment by alexandercerutti** [comment]
@prashant03Dev I guess Apple Developer portal is a good start. What do you need exactly?

**Comment by alexandercerutti** [comment]
@prashant03Dev Nope. That's out of topic.

**Comment by alexandercerutti** [comment]
@prashant03Dev can I close this? Did you solve it?
