### ISSUE TITLE
addBuffer not working for remote images.

### ISSUE THREAD

**Issue by StephanWalters** [alexandercerutti/passkit-generator#187]
## Running OS
Environment: Firebase Cloud Functions Node.js 18 functions.

## Description

When trying to use addBuffer to dynamically add an image to the pass. It doesn't add, but no error is thrown. I am using node-fetch to fetch the image and then converting as an ArrayBuffer.

## Expected behavior
Expecting the background image to be added to the pass.

## Steps to reproduce
Code:
```js
const productImage = await nodeFetch("https image url");
const productImageBuffer = await sellerImage.arrayBuffer();
newPass.addBuffer("background.png", productImageBuffer);
newPass.addBuffer("background@2x.png", productImageBuffer);
```

## Other details

-   [ ] I'm available to open a Pull Request to resolve the problem (after the triage)

**Comment by alexandercerutti** [comment]
Hi @StephanWalters! Thanks for using passkit-generator!

`addBuffer`, as the name says, accepts a NodeJS `Buffer`, which extends (or shares properties with) [`UInt8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array).

An [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) is just a raw data representation, without a specific meaning (e.g. Big Endian or Little Endian notation or byte size for a single cell). To be read, it requires a View.

`UInt8Array` is one of the [TypedArrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) belonging to the Web standard that compose and, as it is a TypedArray, it can act as a View for your `ArrayBuffer`.

An `ArrayBuffer` doesn't own a property `length`, but instead a `byteLength` (I think the reason is exactly this one, to avoid confusion), so it stops right here:

https://github.com/alexandercerutti/passkit-generator/blob/bab4117cb029b00a50077262187fcc2ad9412357/src/PKPass.ts#L412-L417

So, my guess here is that it should work if you do something like:

```js
const productImageAB = await nodeFetch("https image URL").then(res => res.arrayBuffer());
const productImage = Buffer.from(productImageAB);

newPass.addBuffer("name", productImage);
```

Could you please try and let me know?

Thank you!

**Comment by StephanWalters** [comment]
I tried but am still receiving no error and no image in the pass. I am also seeing this warning. But i am also getting a weird user experience. Im currently testing my implementation firing a firebase url request that returns the pass. However, changing to use Buffer.from() returns a 200, but i don't get a pass. Instead Safari (on iPhone) just reloads whatever webpage was on screen prior to me executing my function.



`Argument type Buffer is not assignable to parameter type Buffer.`

I am not sure if this makes a difference, but i am also using PKPass.from (with a small pass.json) instead of the constructor PKPass(). I am doing this because i ran out of memory with my cloud function do using multiple buffers for the first dictionary used in PKPass().

```
      const sellerImage = await nodeFetch(sellerData.photo);
      const productImage = await nodeFetch(productPhoto);

      const sellerImageBuffer = await sellerImage.arrayBuffer();
      const productImageBuffer = await productImage.arrayBuffer();
      const sellerfromBuffer = Buffer.from(sellerImageBuffer);
      const productfromBuffer = Buffer.from(productImageBuffer);

      logger.debug(`sellerData.photo: ${sellerData.photo}`);
      logger.debug(`product photo: ${productPhoto}`);

      newPass.addBuffer("thumbnail@1x.png",
          sellerfromBuffer);
      newPass.addBuffer("thumbnail@2x.png",
          sellerfromBuffer);

      newPass.addBuffer("background.png",
          productfromBuffer);
      newPass.addBuffer("background@2x.png",
          productfromBuffer);
```

**Comment by alexandercerutti** [comment]
May I ask you why you're still using node-fetch, when starting from Node 17, `fetch` is available globally? I see you are running on Node 18. May I ask you to use it to be sure it is specifically compliant with the standard? I don't think this will solve it, but who knows...

> Argument type Buffer is not assignable to parameter type Buffer.

I'm not sure where this happens exactly. Do you have any further details?

> I tried but am still receiving no error and no image in the pass. I am also seeing this warning. But i am also getting a weird user experience. Im currently testing my implementation firing a firebase url request that returns the pass. However, changing to use Buffer.from() returns a 200, but i don't get a pass. Instead Safari (on iPhone) just reloads whatever webpage was on screen prior to me executing my function.

That's kind of weird. Do you have perhaps a repro case that I could use to investigate?

**Comment by StephanWalters** [comment]
@alexandercerutti 
no particular reason. I'm primary is a front end mobile dev (iOS) and self taught myself javascript/Node.js.

As far as: `Argument type Buffer is not assignable to parameter type Buffer.` it seemed to be a type missmatch importing node buffer cleared the warning. `const {Buffer} = require("node:buffer");`

This is index.js firebase onRequest function. I removed a few strings and replaced with HIDDEN, but this is pretty much my exact function. Removing the newPass.addBuffer() will recreate the pass, but removing it wont. Something else, that i see that's odd is with this code (on desktop) it creates a pkpasses bundle, which is 14.4MB (thats crazy large) without the newPass.addBuffer() it will work on safari web and mobile but the pass is much smaller.


```
const {onRequest} = require("firebase-functions/v2/https");

const logger = require("firebase-functions/logger");
const {getDatabase} = require(`firebase-admin/database`);
const {apps} = require(`firebase-admin`);
const database = getDatabase(apps[0]);
const {PKPass} = require("passkit-generator");
const fs = require("fs");
const {Buffer} = require("node:buffer");

exports.generatePassRequest = onRequest({
  timeoutSeconds: 300,
  memory: "4GiB",
}, async (request, response) => {
  const env = process.env.DEPLOYMENT_ENVIRONMENT.toLowerCase();
  const signerKeyPassphrase = process.env.SIGNER_KEY_PASSPHRASE;
  const orderId = request.query.o || null;

  if (orderId === null) {
    logger.error("Order id is null");
    response.status(404)
        .send({success: false, reason: "Unable to generate passes"});
    return;
  }

  const orderSnapshot = await database.ref(`orders/${orderId}`).get();

  if (orderSnapshot == null || orderSnapshot.val() == null) {
    logger.error("Order data is empty");
    response.status(404)
        .send({success: false, reason: "Unable to generate passes"});
    return;
  }

  const orderData = orderSnapshot.val();
  const eventId = orderData.eventId || null;
  const sellerId = orderData.sellerId || null;
  const buyerId = orderData.buyerId || null;
  let buyerName = "Comp Ticket";

  const sellerSnapshot = await database.ref(`users/${sellerId}`).get();


  if (buyerId !== null) {
    const buyerSnapshot = await database.ref(`users/${buyerId}`).get();

    if (buyerSnapshot != null && buyerSnapshot.val() != null) {
      buyerName = buyerSnapshot.val().name || "Comp Ticket";
    } else {
      logger.info("buyer data is empty");
    }
  }


  if (sellerSnapshot == null || sellerSnapshot.val() == null) {
    logger.error("seller data is empty");
    response.status(404)
        .send({success: false, reason: "Unable to generate passes"});
    return;
  }

  const sellerData = sellerSnapshot.val();
  const sellerName = sellerData.name || "";

  if (eventId != null) {
    const eventSnapshot = await database.ref(`events/${eventId}`).get();
    if (eventSnapshot == null || eventSnapshot.val() == null) {
      logger.error("event data is necessary but empty");
      response.status(404)
          .send({success: false, reason: "Unable to generate passes"});
      return;
    }
  }

  const items = orderData.items || null;

  if (items === null) {
    logger.error("order items are null");
    response.status(404)
        .send({success: false, reason: "Unable to generate passes"});
    return;
  }

  logger.debug(`items not nil`);
  logger.debug(`items length count: ${items.length}`);

  const passes = [];

  for (let count = 0; count < items.length; count++) {
    const item = items[count];

    if (item["type"] === "product") {
      let partyString = "";
      const itemParty = item.party || null;
      const productId = item.id;
      const itemPrice = item.price || 0;
      const itemQuantity = item.quantity || 0;

      if (itemParty !== null) {
        partyString = "0";
      }

      const productSnapshot = await database.ref(`products/${productId}`).get();

      if (productSnapshot === null || productSnapshot.val() == null) {
        logger.error(`product id: ${productId} has no data`);
        continue;
      }

      const productData = productSnapshot.val();

      const serialNumber = `${orderId}-${count}-${partyString}`;
      const productName = productData.name || "UNKNOWN";
      const productPhoto = productData.images[0] || "";
      const productDetails = productData.details || "";

      const wwdr = fs.readFileSync(`./passkit/certificates/wwdr/wwdr.pem`);
      const signerCert = fs.
          readFileSync(`./passkit/certificates/${env}/signerCert.pem`);
      const signerKey = fs.
          readFileSync(`./passkit/certificates/${env}/signerKey.pem`);

      // create coupon product pass
      const newPass = await PKPass.from(
          {
            model: `./passkit/models/product.pass`,
            certificates: {
              wwdr: wwdr,
              signerCert: signerCert,
              signerKey: signerKey,
              signerKeyPassphrase: signerKeyPassphrase,
            },
          },
          {
            serialNumber: serialNumber,
            associatedStoreIdentifiers: [6471537147],
            description: productName,
            groupingIdentifier: `pass-group-${orderId}`,
            appLaunchURL: `HIDDEN://products/${productId}`,
            passTypeIdentifier: `pass.com.HIDDEN.order.item`,
            foregroundColor: "rgb(30, 30, 30)",
            backgroundColor: "rgb(230, 230, 230)",
            labelColor: "rgb(30, 30, 30)",
          },
      );

      const sellerImage = await fetch(sellerData.photo);
      const productImage = await fetch(productPhoto);

      const sellerImageArrayBuffer = await sellerImage.arrayBuffer();
      const productImageArrayBuffer = await productImage.arrayBuffer();

      const arr1 = new Uint8Array(sellerImageArrayBuffer);
      const arr2 = new Uint8Array(productImageArrayBuffer);


      logger.debug(`sellerData.photo: ${sellerData.photo}`);
      logger.debug(`product photo: ${productPhoto}`);

      // newPass.addBuffer("thumbnail@1x.png", Buffer.from(arr1));
      newPass.addBuffer("thumbnail@2x.png", Buffer.from(arr1));
     
      newPass.addBuffer("background.png", Buffer.from(arr2));
      newPass.addBuffer("background@2x.png", Buffer.from(arr2));

      newPass.headerFields.push({
        "key": "product-header-field-1",
        "label": "PURCHASED ON",
        "value": "May 25th",
        "textAlignment": "PKTextAlignmentRight",
      });

      newPass.primaryFields.push({
        "key": "product-primary-field-1",
        "label": `Sold by ${sellerName}`,
        "value": productName,
        "textAlignment": "PKTextAlignmentLeft",
      });

      const USDollar = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
      });

      const formattedPrice = USDollar.format(itemPrice);
      newPass.secondaryFields.push({
        "key": "product-secondary-field-2",
        "label": "Price",
        "value": formattedPrice,
        "textAlignment": "PKTextAlignmentLeft",
      });


      newPass.auxiliaryFields.push({
        "key": "product-auxiliary-field-3",
        "label": "Quantity",
        "value": itemQuantity,
        "textAlignment": "PKTextAlignmentLeft",
      });

      newPass.backFields.push({
        "key": "product-back-field-1",
        "label": "PRODUCT DETAILS",
        "value": productDetails,
        "textAlignment": "PKTextAlignmentLeft",
      });

      newPass.backFields.push({
        "key": "product-back-field-2",
        "label": "PRICE",
        "value": formattedPrice,
        "textAlignment": "PKTextAlignmentLeft",
      });

      newPass.backFields.push({
        "key": "product-back-field-3",
        "label": "QUANTITY",
        "value": itemQuantity,
        "textAlignment": "PKTextAlignmentLeft",
      });

      newPass.backFields.push({
        "key": "product-back-field-4",
        "label": "SOLD BY",
        "value": sellerName,
        "textAlignment": "PKTextAlignmentLeft",
      });

      newPass.backFields.push({
        "key": "product-back-field-5",
        "label": "PURCHASED BY",
        "value": buyerName,
        "textAlignment": "PKTextAlignmentLeft",
      });

      newPass.backFields.push({
        "key": "product-back-field-6",
        "label": "ORDER ID",
        "value": orderId.slice(-6),
        "textAlignment": "PKTextAlignmentLeft",
      });

      logger.debug(`pass count: ${passes.length}`);
      passes.push(newPass);
    }
  }

  logger.debug(`pass count: ${passes.length}`);

  const passBundle = PKPass.pack(passes[0]);
  logger.debug("packed passes");
  const passBufferData = passBundle.getAsBuffer();
  response.set("Content-Type", passBundle.mimeType);
  response.status(200).send(passBufferData);
});

```

**Comment by alexandercerutti** [comment]
> Something else, that i see that's odd is with this code (on desktop) it creates a pkpasses bundle, which is 14.4MB (thats crazy large) without the newPass.addBuffer() it will work on safari web and mobile but the pass is much smaller.

It depends on your assets. I do not apply any compression, but I just concatenate the buffers. I made available a "hook" (`.getAsRaw()`) to let people apply their compression and serve the compiled pass. I don't know how many pkpass are you zipping inside your `.pkpasses` zip file, so 14MB might be reasonable based on the sizes of your assets.

By the way, please note that `.pkpasses` that you are trying to output are supported only by Safari (and Mail) and I think only on iPhone; I'm not sure they are supported on Desktop. 

___

About your code, I can suggest you one or two things:

1) Move the reading of the certificates outside the loop. You only need them once.
2) Try to build only one `.pkpass` and check if there's anything different.
3) Try following [the guide for debugging that I set up in the wiki](https://github.com/alexandercerutti/passkit-generator/wiki/Troubleshooting-(Self-help)#through-console-mac-only) and check if, when downloading the pass, some weird error pops on. Apple logs and errors for Apple Wallet are not documented at all, so if you find something weird, I please you to report it here, so it can be useful to other developers in the future.

**Comment by StephanWalters** [comment]
@alexandercerutti i am closing this issue due to human error. I was creating a coupon type pass and the image needed was strip.png. Sorry about that

**Comment by alexandercerutti** [comment]
Don't worry, @StephanWalters! Glad you solved!

It would be awesome if you could leave a 🌟 on the project!

**Comment by StephanWalters** [comment]
> Don't worry, @StephanWalters! Glad you solved!
> 
> It would be awesome if you could leave a 🌟 on the project!

just did! thank you!
