### ISSUE TITLE
Error: Invalid PEM formatted message

### ISSUE THREAD

**Issue by Leykwan132** [alexandercerutti/passkit-generator#192]
## Running OS
MacOS Sonoma 14.3.1

## Running Node Version
v21.6.2

## Description
Error: Invalid PEM formatted message. I am kinda lost when dealing with certs. There is no clear instructions on how to proceed with certs. The wiki stated the key files can be .key but I saw some issues submitted have key ending with .pem. I am puzzled. 

<img width="445" alt="image" src="https://github.com/alexandercerutti/passkit-generator/assets/56620672/023ece02-1cd0-4a60-9634-cef65efc6a9a">

## Steps to reproduce

`  let wwdr = "certs/wwdc.pem";
  let signerCert = "certs/signerCert.pem";
  let signerKey = "certs/signerKey.key";
  let signerKeyPassphrase = "certs/signerKeyPassphrase.key";
  const pass = await PKPass.from({
    model: "models/sample.pass",
    certificates: {
      wwdr,
      signerCert,
      signerKey,
      signerKeyPassphrase,
    },
`

**Comment by alexandercerutti** [comment]
Hi @Leykwan132, thanks for using passkit-generator!

Have you tried, as documentation says, to pass the content of the files instead of their paths?

Let me know!

**Comment by Leykwan132** [comment]
Yes. It's working now but the Console.App is giving me 

`signature verification failed for signer 0`
`Invalid data error reading pass pass.com.quickcard/8j23fm3. Manifest signature did not verify successfully`
`Failed to add pass: 'file:///Users/leykwanchoo/Downloads/Test<decode: can't compose [%20P]>`

I followed the cert generation in terminal which gives me signedKey.key and did "123456" for the generation phrase. I will retry the generation of certs but with macOs this time.

**Comment by alexandercerutti** [comment]
That's a weird error. Let me know if you are able to make it work. I'm not sure why it happened to you but that "0" does not seem good. Did you check your certificates contents?

**Comment by alexandercerutti** [comment]
Hi @Leykwan132 were you able to solve? Can we close this?
