### ISSUE TITLE
Error: Invalid PEM formatted message.

### ISSUE THREAD

**Issue by mazalog** [alexandercerutti/passkit-generator#194]
Hello, I've been trying to solve this error but I can't find a solution.

part of my code:

```javascript
const pass = await PKPass.from({
             /**
              * Note: .pass extension is enforced when reading a
              * model from FS, even if not specified here below
              */
             model: "./src/controllers/tiket-controllers/tickets-wallet/apple/model/custom.pass",
             certificates: {
                 wwdr: fs.readFileSync("./src/controllers/tiket-controllers/tickets-wallet/apple/certs/pass.cer"),
                 signerCert: fs.readFileSync("./src/controllers/tiket-controllers/tickets-wallet/apple/certs/signerCert.pem"),
                 signerKey: fs.readFileSync("./src/controllers/tiket-controllers/tickets-wallet/apple/certs/signerKey.pem"),
                 signerKeyPasphrase: "D1@na08ydt"
             },
         }
```

check the .pem files by applying the following commands

```sh
openssl x509 -in signerkey.pem -noout -text
openssl x509 -in signercert.pem -noout -text
```

I get an error when running the command for signerkey. generate the file again by running the command:

```sh
openssl pkcs12 -in Certificates.p12 -nocerts -out signerKey.pem -passin pass:[my password] -passout pass:[my password]
```

but it still doesn't work, I hope you can help me

**Comment by alexandercerutti** [comment]
Hey @mazalog, thanks for using passkit-generator!

Could you please elaborate on the error you are receiving? That's not very clear.

Thank you

**Comment by alexandercerutti** [comment]
@mazalog I looked at your code: what's this? What is `pass.cer`?

```js
fs.readFileSync("./src/controllers/tiket-controllers/tickets-wallet/apple/certs/pass.cer")
```

If `pass.cer` is what you have before generating `signerCert.pem`, I think you may have skipped some part of the guide for generating the pass, as wwdr is a different file you have to download first and convert next, as stated in the guide.

**Comment by mazalog** [comment]
> @mazalog I looked at your code: what's this? What is `pass.cer`?
> 
> ```js
> fs.readFileSync("./src/controllers/tiket-controllers/tickets-wallet/apple/certs/pass.cer")
> ```
> 
> If `pass.cer` is what you have before generating `signerCert.pem`, I think you may have skipped some part of the guide for generating the pass, as wwdr is a different file you have to download first and convert next, as stated in the guide.
> 
> Can you please verify that you are using the right WWDR certificate? Thank you

I am using the following file as wwdr

![image](https://github.com/alexandercerutti/passkit-generator/assets/66882970/707d5308-0ccd-4a0f-9a75-f52404d762a8)

**Comment by alexandercerutti** [comment]
When you click the link you highlighted, you download a file named `AppleWWDRCAG4.cer`. Are you telling me that you renamed `AppleWWDRCAG4.cer` to `pass.cer`?

**Comment by mazalog** [comment]
correct, I just changed the nomenclature anyway

![image](https://github.com/alexandercerutti/passkit-generator/assets/66882970/8ceb0780-7fde-472e-a655-66a8f7274c31)

**Comment by mazalog** [comment]
> When you click the link you highlighted, you download a file named . Are you telling me that you renamed to ?`AppleWWDRCAG4.cer``AppleWWDRCAG4.cer``pass.cer`

correct, I just changed the nomenclature anyway

![image](https://github.com/alexandercerutti/passkit-generator/assets/66882970/0a28fb7e-ad2e-4d1d-810c-112259d99e2d)

**Comment by alexandercerutti** [comment]
Renaming the WWDR file into just "pass" is one of the craziest thing I ever heard lol
I mean, that helps you to self-sabotage yourself ahah

Anyway, now you have to convert the wwdr file to PEM, hence the error "Invalid PEM file"

**Comment by mazalog** [comment]
I really have no idea how I got to that, maybe I got confused. Thank you

> Cambiar el nombre del archivo WWDR a solo "pasar" es una de las cosas más locas que he escuchado ja, quiero decir, eso te ayuda a autosabotearte a ti mismo ahah
> 
> De todos modos, ahora tienes que convertir el archivo wwdr a PEM, de ahí el error "Archivo PEM no válido", tal como lo hiciste con y `signerCert``signerKey`

I really have no idea how I got to that, maybe I got confused. Thank you

**Comment by mazalog** [comment]
It was solved by placing the wwrd file in the correct format

**Comment by alexandercerutti** [comment]
Glad I could help you! If you could leave a 🌟 to the project, I'd be very happy!
