### ISSUE TITLE
Cannot open generated pass

### ISSUE THREAD

**Issue by Fearix** [alexandercerutti/passkit-generator#209]
Hello,
I have an online shop for event tickets and would now like to add the function that, in addition to the ticket as a PDF, the ticket is also sent as a Wallet Pass by email.
When I tested this, I noticed that I couldn't open the ticket on the iPhone, nor on the Mac when I dragged it into the simulator's Wallet app (nothing happened).

After receiving the payment the following function in nodejs gets triggered:
``` js
async function generateApplePass(uuidString, eventData, phaseTitle, price, passPath) {

      const pass = await PKPass.from({
        model: "/home/backend/custom_modules/data/ticket.pass",
        certificates: {
          wwdr: fs.readFileSync(path.join(__dirname, 'data/certs', 'wwdr.pem')),
          signerCert: fs.readFileSync(path.join(__dirname, 'data/certs', 'signerCert.pem')),
          signerKey: fs.readFileSync(path.join(__dirname, 'data/certs', 'signerKey.pem')),
          signerKeyPassphrase: "..."
        },        
      }, 
        {
          description: `Ticket für ${eventData.title}`,
          serialNumber: uuidString,
        });


        pass.primaryFields.push({
          key: 'event',
          label: 'EVENT',
          value: eventData.title,
        });
        
        pass.secondaryFields.push(
          {
            key: 'phase',
            label: 'PHASE',
            value: phaseTitle,
          },
          {
            key: 'price',
            label: 'PREIS',
            value: `${price}€`,
          }
        );

        pass.auxiliaryFields.push(
          {
            "key": "date",
            "value": eventData.startDateTime,
            "label": "DATUM",
            "dateStyle": "PKDateStyleMedium",
            "timeStyle": "PKDateStyleShort",
            "ignoresTimeZone": true,
            "isRelative": false
          },
          {
            "key": "location",
            "value": getPassLocation(eventData),
            "label": "LOCATION",
          }
        );

        pass.setBarcodes({
          message: uuidString,
          format: 'PKBarcodeFormatQR',
          messageEncoding: 'iso-8859-1'
        });

        pass.setExpirationDate(new Date(eventData.endDateTime));
        pass.setRelevantDate(new Date(eventData.startDateTime));      

        const bufferData = pass.getAsBuffer();
        fs.writeFileSync(`cache/${passPath}`, bufferData);        
}
```

This is the content of my ticket.pass:
![icon](https://github.com/user-attachments/assets/78b7533a-6c76-4d22-94bf-b0ca2e641604)
![icon@2x](https://github.com/user-attachments/assets/729b79d4-3665-4f0b-a460-7efd31d85501)
![logo@2x](https://github.com/user-attachments/assets/83f7e757-823e-43ca-befc-720cf0aa63e9)
![logo](https://github.com/user-attachments/assets/41fd1165-0a69-418b-8964-c24f958add09)
[pass.json](https://github.com/user-attachments/files/16313869/pass.json)

When I renamed the .pkpass file I received to .zip and extracted the contents, I got the following files. The content looks correct to me, but it is my first time working with passes:
[manifest.json](https://github.com/user-attachments/files/16313919/manifest.json)
![icon](https://github.com/user-attachments/assets/faf36955-66f4-412f-84be-fa5b5a0bb21f)
![icon@2x](https://github.com/user-attachments/assets/f1fcfcf5-2a3d-455b-a2c2-3a8066021189)
![logo](https://github.com/user-attachments/assets/9d0db5c3-be65-4564-b648-e359f97d20b5)
![logo@2x](https://github.com/user-attachments/assets/3d187c56-7058-45df-96c4-eb579406a566)
[pass.json](https://github.com/user-attachments/files/16313920/pass.json)

The folder also contains a signature file, but I can't upload it here.

I have already checked the .pkpass file with an online validator and got this result:
![Bildschirmfoto 2024-07-19 um 17 24 38](https://github.com/user-attachments/assets/c34d88a2-c81a-417b-80b9-f676d8130cc9)

Does anybody know what I'm doing wrong?
Thanks in advance

**Comment by alexandercerutti** [comment]
@Fearix Hi, I’m unable to look at you issue right now. I’ll look at it on Monday

**Comment by alexandercerutti** [comment]
Hi @Fearix, I had a bit of time to read your issue. Did you try to check if Console.app gives you any log? It is likely you are going to find things there, as when a pass doesn't open, it fails silently and logs things.

To debug, I created a guide in wiki that I cannot link you now because I'm from my phone.

Let me know.

**Comment by Fearix** [comment]
Thanks for the quick help @alexandercerutti.
I was able to fix it by following the debugging instructions.
Apparently Apple always requires a time zone for the ISO DateTime strings, which I was missing.

**Comment by alexandercerutti** [comment]
Glad you solved!
May I ask you to leave a star on the project? 🌟
