### ISSUE TITLE
Passes getting created locally but not when deployed on a nextjs project

### ISSUE THREAD

**Issue by shriharip** [alexandercerutti/passkit-generator#210]
## Running OS
macOS 14.3.1 (23D60). local
linux flavour on cloud

"passkit-generator": "^3.1.11",
node version : 20.11.0

## Description

I have a nextjs project with app folder. `nextjs version is 14.1.0` .
I have created the following folder structure: 
- src
  - app
  - lib
    - wallet_models/kepass.pass
      - icon.png
      - logo.png
      - pass.json
      
 my pass.json file is as follows
```
{
  "formatVersion": 1,
  "passTypeIdentifier": "pass.com.ccc.keypass",
  "serialNumber": "nmyuxofgna",
  "teamIdentifier": "JXXXXXX7PA",
  "webServiceURL": "https://example.com",
  "authenticationToken": "vxwxd7J8AlNNFPS8k0a0Ffasdf12Fdc",
  "relevantDate": "2034-07-03T13:00-08:00",
  "locations": [
    {
      "longitude": 12.5683,
      "latitude": 55.6761
    }
  ],
  "organizationName": "XXxX ApS",
  "description": "Description of the company",
  "backgroundColor": "rgb(0,0,0)",
  "foregroundColor": "rgb(255,255,255)",
  "labelColor": "rgb(255,255,255)",
  "generic": {
    "primaryFields": [
      {
        "key": "Desc",
        "value": "Your Personal KeyPass"
      }
    ]
  }
}
```

When i call the pass kit generator to genearate pass. It creates the pass when I run it locally and also when I run `next build` ( which is the production version) and serve it locally. 
However, on deploying, it fails with the error
` Cannot import model: directory src/lib/wallet_models/keypass.pass not found. `

## Steps to reproduce

This is the code for generating the pass
```

import { PKPass } from "passkit-generator";
import { type NextRequest } from "next/server";
import path from "path";

export async function GET(request: NextRequest) {


  const searchParams = request.nextUrl.searchParams;
  const guestUserId = searchParams.get("userId") as string;
  const fullname = searchParams.get("fullname") as string;

  const getAppleCertificatesFromEnv = () => {
    return {
      wwdr: process.env.WWDR,
      signerCert: process.env.SIGNER_CERT,
      signerKey: process.env.SIGNER_KEY,
      signerKeyPassphrase: process.env.SIGNER_PASSPHRASE
    }
}

  const { wwdr, signerCert, signerKey, signerKeyPassphrase } = getAppleCertificatesFromEnv();

  const pass = await PKPass.from(
    {
      model: path.join(path.dirname('./'), 'src/lib/wallet_models/keypass.pass'),
      certificates: {
        wwdr,
        signerCert,
        signerKey,
        signerKeyPassphrase,
      },
    },
  );

  const QRdata = {
    guestUserId,
  };

  const qrMessageData = JSON.stringify(QRdata);

  pass.setBarcodes({
    format: "PKBarcodeFormatQR",
    message: qrMessageData,
    messageEncoding: "iso-8859-1",
  });

  pass.secondaryFields.push({
    key: "name",
    value: fullname,
    label: "Name",
  });

  return new Response(pass.getAsBuffer(), {
    headers: {
      "Content-type": pass.mimeType,
      "Content-disposition": `attachment; filename=myPass.pkpass`,
    },
  });
}

```
There is not much happening on this end.
I am ready to share more info on telegram if it is required. 
Would be really grateful if you could point out what could I be doing wrong or is it some issue?

## Were you able to verify it by using (and changing) the examples?

 No

## Other details

-   [x] I'm available to open a Pull Request to resolve the problem (after the triage)

I am really thankful for the project, i have starred it and also loved using the `pkvd` creator app. So much nice work here. I am also planning to use the webservices functionality ;)

**Comment by alexandercerutti** [comment]
Hi @shriharip thanks for using passkit-generator, PKVD and the rest! Very glad you like them!

I've never used Next.JS directly, but the error you show me seems something about how Next.JS is building and bundling things. So, nothing strictly about passkit-generator itself.

```js
path.join(path.dirname('./'), 'src/lib/wallet_models/keypass.pass')
```

This thing is just a "random" string, an anonymous string that gets used then by passkit-generator through the `node:fs` (the included one).

I can guess that when you deploy and build your application, you are not uploading your model as an asset and therefore the application is not finding it, which it can actually do when you run it locally.

I think your bundled application is going to be outputted in either `dist` or `lib` or `build` folders. Of course, as your library is in the `src` folder, it will not get published along with the rest.

I'm not even sure there's a way you can do that. Maybe you can use the `public` folder but I think the model would be accessible on the web if you know the path.

I want to end by saying that I think that if you import the single assets just like a Javascript module (this import should be then handled by NextJS and Webpack beneath), you should be also able to use the non-template way with passkit-generator.

Something like:

```js
import logo2x from "./logo@2x.png";

...


Let me know.
new PKPass({
    "logo@2x": logo2x
    ...
}, {
    signerCert: "..."
    ...
});
```

**Comment by shriharip** [comment]
Yeah, I also thought so. I have been working on the input you gave . I  still have to find a way to load the assets properly. Will keep you updated. Clearly not a bug on passkit side, just wanted some pointers. Thanks again.

**Comment by alexandercerutti** [comment]
You are welcome! I guess we can close this now, isn't it? :)

**Comment by santyas** [comment]
@shriharip How has this been resolved? Is it possible to see a working example? Thank you in advance :)

**Comment by shriharip** [comment]
@santyas , I have followed @alexandercerutti  suggestion in creating the passes. Though I cannot give complete working example I will try to explain here what I did.

My main issue was having the static assets like logo and icon being used, since these assets were somehow packaged differently with webpack and next. 

```
	const logoResponse = await fetch(logoUrl);
	const iconResponse = await fetch(iconUrl);

	const logoBuffArray = await logoResponse.arrayBuffer();
	const iconBuffArray = await iconResponse.arrayBuffer();

const pass = new PKPass(
		{}, getAppleCertificatesFromEnv,
		{
			"formatVersion": 1,
			"webServiceURL": "https://web.com,
			"passTypeIdentifier": "pass.com.comp.prod",
			"teamIdentifier": teamIdentifier,
			"authenticationToken": authenticationToken,
			"serialNumber": serialNumber,
			"organizationName": "OrgName ApS",
			"description": "The pass..",
			"backgroundColor": "rgb(0,0,0)",
			"foregroundColor": "rgb(255,255,255)",
			"labelColor": "rgb(255,255,255)",
		}
	);

	pass.addBuffer("icon.png", Buffer.from(iconBuffArray))
	pass.addBuffer("logo@3x.png", Buffer.from(logoBuffArray))
	pass.type = 'generic';

// add primary fields, QRcode , secondary etc. to pass and finally 

return new Response(pass.getAsBuffer(), {
		headers: {
			"Content-type": pass.mimeType,
			"Content-disposition": `attachment; filename=myPass.pkpass`,
		},
	});
```
I am working on improving the performance since this takes quite a hit.

**Comment by alexandercerutti** [comment]
@shriharip I suggest you using `Promise.all` for this.

```js
const [logoBuffer, iconBuffer] = await Promise.all([
    fetch(logoUrl).then(r => r.arrayBuffer()),
    fetch(iconUrl).then(r => r.arrayBuffer()),
]);
```

By doing this, you are not waiting any `fetch` to return the HTTP Headers (in fact, `fetch` promise awaits for the headers, while `.text()`, `.blob()`, `.arrayBuffer()` wait for the response to arrive entirely) and you are doing things concurrently.

**Comment by santyas** [comment]
@shriharip Thank you so much for your example, I will try it today :)

**Comment by santyas** [comment]
@alexandercerutti First of all, I want to thank you and congratulate for your work and help you provide us! It's a great library.

I am new here so I'm not sure if this is the right place, but as I understand passkit-generator only creates new passes. But what if I want to scale the shriharip example to handle pass updates? ie: create another api route to patch some pass fields using an "pass id" to find it and update or something like that. Thanks :)

**Comment by alexandercerutti** [comment]
@santyas thank you for using it! I think you should open a new issue for further questions. The risk is this becoming a collector of unrelated things.

> passkit-generator only creates new passes. But what if I want to scale the @shriharip example to handle pass updates? ie: create another api route to patch some pass fields using an "pass id" to find it and update or something like that. Thanks :)

Yes, exactly. Passkit-generator is the basic brick for generating passes. I created a few more libraries to integrate the update of passes. Check the begin of the Readme file for them. :)
