### ISSUE TITLE
Cannot create pass from a template. "serialNumber" is not allowed

### ISSUE THREAD

**Issue by kyle-ssg** [alexandercerutti/passkit-generator#212]
## Running OS

MacOS 14.5

## Running Node Version
v22.4.0

## Description

As far as I understand it, a serial number would allow users to download multiple passes.

## Expected behavior

I would have expected the following to work but get "Cannot create pass from a template. "serialNumber" is not allowed"

```
    const stringData = `${Buffer.from(`${req.query.data}`, 'base64')}`
    const parsed = JSON.parse(stringData)

    const pass = await PKPass.from({
      certificates: {
        signerCert: `${parseCert('WALLET_SIGNER_CERT')}`,
        signerKey: `${parseCert('WALLET_SIGNER_KEY')}`,
        signerKeyPassphrase: process.env.WALLET_SIGNER_PASSWORD,
        wwdr: `${parseCert('WALLET_WWDR')}`,
      },
      model: path.join(process.cwd(), 'apple-wallet', 'model.pass'),
      serialNumber: `${parsed.email}`,
      type: 'storeCard',
    })
```

## Steps to reproduce
Code above

## Other details

I'm most likely either specifying the serial number incorrectly or misunderstanding its purpose, please let me know!

**Comment by alexandercerutti** [comment]
Hi @kyle-ssg, thanks for using passkit-generator!

Yes, you are specifying it badly. If you look [at the documentation](https://github.com/alexandercerutti/passkit-generator/wiki/API-Documentation-Reference#-from-a-template), a first argument is an object that contains `certificates` and `model`. A second argument contains the props you want to override from your model.

Please note that `type` is not one of them, as it is a property you can set.

Let me know.

**Comment by kyle-ssg** [comment]
I'm so dumb 😆. Thank you for the lightning response.

**Comment by alexandercerutti** [comment]
You are welcome ;)
If you could leave a 🌟 on the project, that would be awesome :D
