### ISSUE TITLE
Facing difficulties while designing the passs

### ISSUE THREAD

**Issue by prashant03Dev** [alexandercerutti/passkit-generator#213]
@alexandercerutti 

Currently i'm struggling while updating the pass,As we are showing some details on auxillary field,and we want to add some more fields values to that,but they are getting mixtured.

Below we are sharing the design of the template

```ts
const passCreated: Awaited<PassKit.PKPass> = await this.walletService.createPass(
                'Event.pass',
                this.user.uuid,
                `${generateUuidV4()}/vehicle-id-card-pass`,
            );

            // make passCreated
            passCreated.type = PassType.EVENT_TICKET;

            passCreated.headerFields.push({
                key: 'issuedBy',
                label: 'Issued By',
                value: `Organization name`,
            });

            passCreated.primaryFields.push(
                {
                    key: 'name',
                    label: 'Insured name',
                    value: `value`,
                },
                {
                    key: 'description',
                    label: 'Description',
                    value: `${this.payload.description}`,
                },
            );

            passCreated.secondaryFields.push(
                {
                    key: 'startDate',
                    label: 'Effective Date',
                    value: `${formatDate(this.payload.effectiveDate, DateTimeFormatEnum.MM_DD_YYYY)}`,
                },
                {
                    key: 'expirationDate',
                    label: 'Policy Expiration',
                    value: `${formatDate(this.payload.expirationDate, DateTimeFormatEnum.MM_DD_YYYY)}`,
                },
            );

            passCreated.auxiliaryFields.push(
                {
                    key: 'policyNo',
                    label: 'Policy Number',
                    value: `${this.payload.policyNo}`,
                },
                {
                    key: 'vin',
                    label: 'VIN',
                    value: `${this.payload.vin}`,
                    textAlignment: 'PKTextAlignmentRight',
                },
            );

            passCreated.auxiliaryFields.push(
                {
                    key: 'make',
                    label: 'Make',
                    value: `${this.payload.make}`,
                },
                {
                    key: 'model',
                    label: 'Model',
                    value: `${this.payload.model}`,
                    textAlignment: 'PKTextAlignmentRight',
                },
            );

            const buffer = passCreated.getAsBuffer();

            await fs.writeFile('vechile-card.pkpass', buffer);

            // await this.upsertPass();

            response.setHeader('Content-Type', 'application/vnd.apple.pkpass');
            response.setHeader('Content-Disposition', `attachment; filename="vehicle-pass.pkpass"`);

            response.send(buffer);
}
```

As when adding make and model field,they both got attached to policynumber field,

Suggest us the way to get the design of the pass to be update,as well as share some pass design to follow the principle

Thanks & Regards,
Prashant

**Comment by alexandercerutti** [comment]
Hi @prashant03Dev,

What do you mean by "mixtured"? What is the result you would expect?

P.s. no need to tag me, as I receive all the issues.

**Comment by prashant03Dev** [comment]
@alexandercerutti 

Mixtured means we are having glitch in design part,As I'm sharing a snapshot with you

<img width="363" alt="pass" src="https://github.com/user-attachments/assets/e95e9cd4-038c-44cc-841b-fd4934d751e1">

**Comment by prashant03Dev** [comment]
> @alexandercerutti
> 
> Mixtured means we are having glitch in design part,As I'm sharing a snapshot with you,
> 
> As you can see,we are trying to shift Make and model key to down line.
> 
> <img alt="pass" width="363" src="https://private-user-images.githubusercontent.com/122872400/360387231-e95e9cd4-038c-44cc-841b-fd4934d751e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjIwMjIsIm5iZiI6MTcyNDMyMTcyMiwicGF0aCI6Ii8xMjI4NzI0MDAvMzYwMzg3MjMxLWU5NWU5Y2Q0LTAzOGMtNDRjYy04NDFiLWZkNDkzNGQ3NTFlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxMDE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDgyYzFiZTliZTcyNjM5ZGM5MTFmOGJjMjA5MThiOWVlNjZlOWMxNmFkNTczZTU3ZjY5MzRhYmYzNTlmYWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aUhYw2urGTkWTK-Vs-iMjEvt28etM7lz7RAmbwAcfzk">


Can we get quick update on this,how can we adjust

**Comment by prashant03Dev** [comment]
@alexandercerutti are you there,As this issue are need to deploy ASAP,So can you take a time of yours to help us in this pass design.

**Comment by alexandercerutti** [comment]
No. I've other things to do in my life.

When you'll decide to contribute financially to the project on OpenCollective, I'll be happy to support you with the higher priority I can give you. Otherwise, you'll have to wait as I get free.

**Comment by prashant03Dev** [comment]
Thanks @alexandercerutti,I'm closing this issue.

**Comment by alexandercerutti** [comment]
I guess you solved. Nice if so. 🚀
