### ISSUE TITLE
Where Do i get the passkey.pem

### ISSUE THREAD

**Issue by jtuttas** [alexandercerutti/passkit-generator#218]
Hello, setting up a Projekt for IOS Wallets three years ago. Unfortunately the certificates are expired and all my knowledge is  gone ;-(, so can you please help. 

I think I've set up everything correct.  Downloaded the new AppleWWDRCA, convert it to a pem. Generate a pass.cert and convert it to a signerCert.pem.

But what is the **passkey.pem** ? Where did I get it ? Any help ist welcome !

best regards

Jtuttas

**Comment by alexandercerutti** [comment]
Hi @jtuttas, thanks for using passkit-generator!

I think you are referring to signerKey, isn't it?

If so, that's the key for your pass certificate.

Follow the guide in the Wiki for more and let me know if you have any further question!

**Comment by jtuttas** [comment]
Thanks an lot, I guess I've solved the Problem, I'am using the V2 Version!
