### ISSUE TITLE
Use strings instead of pem file for passkit

### ISSUE THREAD

**Issue by timmy4all** [alexandercerutti/passkit-generator#22]
Hi,
We are trying to inject the private key and certificates to the node service for creating passes. This implementation however requires us to provide a path to the key and certificate pem files. Is there a way to pass encoded string instead? That way we can store the certs and keys in application memory and inject at run time.

**Comment by alexandercerutti** [comment]
Hi, @timmy4all 
Yes, it is possible to pass directly the content of the file to the configuration. [An issue](https://github.com/alexandercerutti/passkit-generator/issues/11) that was requesting this to be implemented, has already been opened and the request has been satisfied 😄.

**Comment by timmy4all** [comment]
Great. i will give this a shot. I am assuming i can still use node v8.

**Comment by alexandercerutti** [comment]
Be sure to use Node v8.1 or higher.

**Comment by WayneDT** [comment]
I have tried this and it just fails.
is there an example?
my certificates object contains a string version of the keys
certificates: {
        wwdr: env.apple_wwdr,
        signerCert: env.apple_signerCert,
        signerKey: {
          keyFile: env.apple_signerKey,
          passphrase: CertificatePaths.applePassphrase,
        },
      },
