### ISSUE TITLE
EventTicker Poster layout and NFC entitlements questions

### ISSUE THREAD

**Issue by alexandercerutti** [alexandercerutti/passkit-generator#227]
Hi @alexandercerutti , this thread has been very helpful in finding the right documentation for the new apple passes. 
However I am facing an issue which is when trying to install the new pass to my iphone (ios 18.1) it is saying error "Sorry, your pass cannot be installed to passbook at this time "

I am attaching a link to my pkpass file, if anyone here can debug it, it would be very helpful
https://c10-passes.s3.amazonaws.com/2cfaa8e6-8695-4032-ab90-40fdc65ea750_testpass.pkpass

 This is how my code looks like
```
const pass = new PKPass({
        'pass.json': Buffer.from(JSON.stringify(passjson)),
        'artwork.png': fs.readFileSync(path.join(`${__dirname}/../`, 'images', 'artwork.png')),
        'artwork@3x.png': fs.readFileSync(path.join(`${__dirname}/../`, 'images', 'artwork@3x.png')),
        'icon.png': fs.readFileSync(path.join(`${__dirname}/../`, 'images', 'icon.png')),
        'logo.png': fs.readFileSync(path.join(`${__dirname}/../`, 'images', 'logo.png')),
        'strip@3x.png': fs.readFileSync(path.join(`${__dirname}/../`, 'images', 'strip@3x.png')),
        'venueMap.png': fs.readFileSync(path.join(`${__dirname}/../`, 'images', 'venueMap.png')),
      }, {
        wwdr: fs.readFileSync(path.join(`${__dirname}/../`, 'AppleWWDRCA.pem')),
        signerCert: fs.readFileSync(path.join(`${__dirname}/../`, 'signerCert.pem')),
        signerKey: fs.readFileSync(path.join(`${__dirname}/../`, 'signerKey.pem')),
        signerKeyPassphrase: config.get('appleWallet')
      })
```
you can check the pass.json and other meta files in the pkpass after unzipping it 

Thanks again!!
 

_Originally posted by @sudodm in https://github.com/alexandercerutti/passkit-generator/issues/205#issuecomment-2455488961_

**Comment by alexandercerutti** [comment]
Hi @sudodm, thanks for using passkit-generator!

I've moved your message to a new issue because it doesn't fit in that discussion!

Did you try checking Console.app if it says any message, as per the dedicated Wiki page?

Let me know!

**Comment by sudodm** [comment]
Hi @alexandercerutti , I am not sure how to check on Console.app , can you describe please ?

**Comment by sudodm** [comment]
@alexandercerutti  And, it would be really helpful if you can provide a demo or a test pkpass with new posterEventTicket that I can install on my phone, Thanks.

**Comment by alexandercerutti** [comment]
@sudodm A demo is available in the example folder

**Comment by sudodm** [comment]
I checked the examples folder but it has the model for the pass and not the pkpass itself. Can you share a demo pkpass file please ?

**Comment by alexandercerutti** [comment]
@sudodm Sorry, I can't share one. I cannot share any of the details used, included `passTypeIdentifier` or `teamIdentifier`, to generate such pass.

Yes, in the `examples` folder you can see the models you can use. If you have NFC-Entitled Certificates, you can use yours and use such models to start.

For what concerns the `Console.app` inspection, here is the guide in the wiki: https://github.com/alexandercerutti/passkit-generator/wiki/Troubleshooting-(Self-help)#through-console-mac-only

I'm going to give a look at the pass you generated to check if I can find any more details.

**Comment by alexandercerutti** [comment]
`Console.app` says this on my Mac:

```
Invalid data error reading pass pass.com.token.counterten.app/2cfaa8e6-8695-4032-ab90-40fdc65ea750. Passes with an NFC dictionary or a Personalization JSON file must be signed with an enhanced Passbook certificate.
```

My guess is that you don't have NFC-Entitled certificates. Is it like this?

**Comment by sudodm** [comment]
@alexandercerutti  Yes, I don't have NFC-Entitled certificates. Thanks for mentioning it as when I removed the nfc block from pass.json it worked but unfortunately showed the old layout. 

I have two main questions:

1. How to get the **NFC-Entitled certificates**
2. If I don't have the NFC-Entitled certificates and want to use the new poster event ticket layout, is it even possible ?

**Comment by alexandercerutti** [comment]
1) Obtaining NFC-Entitled certificates is a hard matter, as you need to require the entitlement for generating them to Apple. They will ask you things, like "why", "do you have business behind" or "do you have NFC terminals to use" and things like this. Obtaining them is quite difficult. I'll leave you a link where explains how it works. There, you can find a link to a form to request the permission: https://developer.apple.com/wallet/loyalty-passes/#implementation

2) Nope, sadly it isn't. I had someone to provide me some because I don't have them either (that's the reason I cannot distribute a working pkpass).

**Comment by sudodm** [comment]
Thanks @alexandercerutti for answering my questions!

**Comment by alexandercerutti** [comment]
You are welcome! I'll close this if you don't have any further questions!

If you could leave a ⭐ on the project, that would be awesome! 🚀

**Comment by yashinficare** [comment]
Hi, I want to enable NFC in pkpass, I have created a new certificate with NFC check. I have used below code for pass.json to enable NFC.
pass.nfc = new NFC
{
message = mbr.MembershipID.ToString(),
encryptionPublicKey="UU5g65SpyhFa9nJ1nnSiXWU88KZZCb7Ah2iOB/TwuNOMKcMYTY5WdUG7zvK63OEqdaj4P8c7vk7AtBbe+LgnOg==",
requiresAuthentication = false
};

Now after using this, the pass if not opening, if I use "nfc":[{...}], then it opens the pass, but if I use nfc object as mentioned in the apple documentation the pass is not opening.

Please guide and let me know where I am going wrong. Please provide a solution for this, Ill appreciate your help. Thank you so much.

I want to enable NFC in my pkpass, I am already using pkpass and its working great, I am using Event Ticket. Now, I want to enable the NFC to my pkpass.`

**Comment by alexandercerutti** [comment]
Hi @yashinficare, thanks for using passkit-generator!

What is exactly `new NFC()`? Where did you find it?

**Comment by yashinficare** [comment]
Actaully I am using C#, so for that I have created a object as per the required json mentioned in the apple documentation.

**Comment by alexandercerutti** [comment]
So I guess this is not related to this repository and this project. I'm afraid I cannot help you, as I don't know C#.

Don't know which library are you using, but you should verify if such library supports poster event tickets (as I guess you are doing, since you wrote in this topic)

**Comment by yashinficare** [comment]
Can you please confirm, do we only have to allow NFC tag while creating a certificate, or do we have to ask for a special permission from apple to access nfc and enable nfc in our pkpass certificate.

**Comment by alexandercerutti** [comment]
Certificates **can** have inside them the permission of using NFC. However, in order to generate some with such permission, you must receive the permission from Apple first.

**Comment by yashinficare** [comment]
Thank you for you help.

**Comment by yashinficare** [comment]
How can we approach the apple for having this permission, or can we directly approach them via customer support.

**Comment by alexandercerutti** [comment]
If you look above, in [this comment](https://github.com/alexandercerutti/passkit-generator/issues/227#issuecomment-2455735809), you'll get all the informations you are looking for
