### ISSUE TITLE
Using pass.setNFC() does not allow pass to open in wallet preview (desktop) or on device

### ISSUE THREAD

**Issue by rugor** [alexandercerutti/passkit-generator#231]
## Running OS

Sequoia 15.1

## Running Node Version

20.17.0

## Description

I have a working pass generating service. I am attempting to add NFC to generated passes. I use setNFC as from here: https://github.com/alexandercerutti/passkit-generator/wiki/API-Documentation-Reference#setnfc

But then the pass breaks! 

The pass does not open in Apple Wallet preview (double clicking pass in desktop Finder) and when I send to my phone it will not open in Apple Wallet on device.

Unzipping the contents of pkpass shows that the .setNFC has added json dictionary items to pass successfully, however pass will not open.

Extracted (and redacted) pass.json:

```
{
  "formatVersion": 1,
  "description": "Demo",
  "organizationName": "Demo",
  "passTypeIdentifier": "pass.com.demodemodemo.passmaker",
  "teamIdentifier": "6G2N5XXXXX",
  "foregroundColor": "rgb(34, 34, 34)",
  "backgroundColor": "rgb(255, 248, 239)",
  "labelColor": "rgb(34, 34, 34)",
  "nfc": {
    "message": "Demo Member ID: rc43k2bmvtc17f9",
    "encryptionPublicKey": "MDkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDIUv8T3zYkX3WxceIH6lqQlUmoku4fd/96zSw9n4e2wU/Sck=",
    "requiresAuthentication": false
  },
  "storeCard": {
    "headerFields": [
      {
        "key": "memberNumber",
        "label": "MEMBER NUMBER",
        "value": "000 000 043",
        "textAlignment": "PKTextAlignmentNatural"
      }
    ],
    "primaryFields": [],
    "secondaryFields": [],
    "auxiliaryFields": [
      { "key": "name", "label": "NAME", "value": "Joe Smith" },
      { "key": "spacer", "label": "", "value": "" },
      { "key": "expiryDate", "label": "MEMBER SINCE", "value": "2024 12 18" }
    ],
    "backFields": [
      {
        "key": "accountInfo",
        "label": "Joe Smith",
        "value": "Member Number: 000 000 043"
      }
    ],
    "additionalInfoFields": []
  },
  "authenticationToken": "4c6681cb348625a1838fec5ee0uffbfb631981295d239490ed81e4d6128te321",
  "webServiceURL": "https://demo-webservice.app/api/apple-webservice",
  "serialNumber": "rc43k2bmvtc17f9",
  "barcodes": [
    {
      "message": "http://localhost:3000/pass/rc43k2bmvtc17f9",
      "format": "PKBarcodeFormatQR",
      "messageEncoding": "iso-8859-1"
    }
  ]
}
```

## Expected behavior

I would expect the pass to still work (pass openable) after adding data via setNFC()
I am not expecting the NFC to work because there are many steps to do that. But I want to at least have the pass installable to apple wallet to make the steps towards testing and troubleshooting.

## Steps to reproduce

Generate a pass using passkit-generator:

```
const new_pass = await PKPass.from(
        {
          model: model_path,
          certificates: {
            wwdr: certs.wwdr,
            signerCert: certs.signer_cert,
            signerKey: certs.signer_key,
            signerKeyPassphrase: process.env.SIGNER_KEY_PASSPHRASE
          }
        },
        {
          authenticationToken: auth_token, // this is the authentication token that the device uses to authenticate the request. it does not change
          webServiceURL:
            'https://my-webservice', 
          serialNumber: id,
          description: 'My desc',
          foregroundColor: 'rgb(34, 34, 34)',
          backgroundColor: 'rgb(255, 248, 239)',
          labelColor: 'rgb(34, 34, 34)'
        }
      )
```

Add NFC: 

```
new_pass.setNFC({
        message: `Demo Member ID: ${id}`,
        encryptionPublicKey: process.env.NFC_ENCRYPTION_PUBLIC_KEY,
        requiresAuthentication: false
      })
```

## Other details
Thanks for project. Very good and helpful.

-   [ ] I'm available to open a Pull Request to resolve the problem (after the triage)

**Comment by alexandercerutti** [comment]
Hey @rugor, thanks for using passkit-generator!
I know, obtaining nfc certificates is a pain in the ass and very long procedure.

If I remember correctly, using `nfc` property is bound to the usage of an NFC certificate.
You have to check in `Console.app` which message it says to you when you try to open it.

Let me know.

**Comment by rugor** [comment]
Ok thanks i have done what you suggest and result is here:

![Screenshot 2024-12-18 at 2 39 03 PM](https://github.com/user-attachments/assets/7083b644-fcdc-49e8-af75-4800fc08bf66)

I think i followed an old tutorial (few years old) that showed making public / private keys independently and now maybe these keys need to be special from Apple? 

thanks for the help and sorry to bother you! a little cloudy waters here

**Comment by alexandercerutti** [comment]
That's exactly the message I was thinking of.

The procedure for creating certificates has always been the same.

However, if you have the entitlements given from Apple, you can export a different kind of certificate from Apple Developer, that allows you to generate an NFC pass.

Obtaining one is not easy. Lot of requirements AND you must be a business with a specific structure.

No bother. I'm here to help and put a little bit of order in this world of passes eheh.

**Comment by rugor** [comment]
Great, and thanks for the helpful npm package.

**Comment by alexandercerutti** [comment]
You are welcome!

If you could leave a ⭐️ on the project, that would be great! 🚀
