### ISSUE TITLE
Fail to serve pass to iOS

### ISSUE THREAD

**Issue by hhhlau** [alexandercerutti/passkit-generator#24]
This maybe a stupid issue..
I built a pass successfully but it fail to pop up when I accessing the URL form my iPhone. However, the pass is loaded correct on MAcOS's Safari... Any idea any steps I have messed up? I am working with the example code with only updated the certs path & some pass content..
Thanks for the awesome work!

![image](https://user-images.githubusercontent.com/8468467/58263985-a99e8d80-7daf-11e9-9961-e9981c23755c.png)

**Comment by alexandercerutti** [comment]
Hi @hhhlau, I have no clue about this 🤔
It is probably a network/mac options problem.
I'm not in a good position to test this, as I have a Windows PC and I've found no way to open the port to node.js process (yes, I searched and tried different solutions). My Mac is a VM that have that problem too right now. I don't know if that is a router problem or not.

**Comment by tinovyatkin** [comment]
ZIP archive in pass must actually contain uncompressed files to be able to open on iOS.

**Comment by hhhlau** [comment]
> Hi @hhhlau, I have no clue about this 🤔
> It is probably a network/mac options problem.
> I'm not in a good position to test this too, as I have a Windows PC and I've found no way to open the port to node.js process (yes, I searched and tried different solutions). My Mac is a VM that have that problem too right now. I don't know if that is a router problem or not.

Maybe let me try on a Linux platform or container

**Comment by hhhlau** [comment]
> ZIP archive in pass must actually contain uncompressed files to be able to open on iOS.

@tinovyatkin can you explain a little bit more??

**Comment by alexandercerutti** [comment]
> ZIP archive in pass must actually contain uncompressed files to be able to open on iOS.

@tinovyatkin Well, that's weird, because if @hhhlau said he used one of the available examples and model, there is nothing compressed inside 🤔🤔

@hhhlau since I'm a bit in difficult to test the passes, what I do is sent me the pass in my own private chat "Saved Messages" on Telegram from Pc and then open it from the iPhone. Can you try something like this? If the pass opens from Telegram there shouldn't be any problem.

___

P.s. @tinovyatkin can you please answer to my email? 😂 Thank you

**Comment by gweit** [comment]
@hhhlau i ran into a similar problem a few ago, do you use node to serve the pass?

If yes, could you please paste the code of the code of the route in here so i can take a look.

**Comment by hhhlau** [comment]
> @hhhlau i ran into a similar problem a few ago, do you use node to serve the pass?
> 
> If yes, could you please paste the code of the code of the route in here so i can take a look.

@gweit , yes I am using node on Mac to serve pass and I am just using the example code

**Comment by hhhlau** [comment]
> > Hi @hhhlau, I have no clue about this 🤔
> > It is probably a network/mac options problem.
> > I'm not in a good position to test this too, as I have a Windows PC and I've found no way to open the port to node.js process (yes, I searched and tried different solutions). My Mac is a VM that have that problem too right now. I don't know if that is a router problem or not.
> 
> Maybe let me try on a Linux platform or container

I have tried on CentOS but it perform similar as it on MacOS

**Comment by hhhlau** [comment]
> > ZIP archive in pass must actually contain uncompressed files to be able to open on iOS.
> 
> @tinovyatkin Well, that's weird, because if @hhhlau said he used one of the available examples and model, there is nothing compressed inside 🤔🤔
> 
> @hhhlau since I'm a bit in difficult to test the passes, what I do is sent me the pass in my own private chat "Saved Messages" on Telegram from Pc and then open it from the iPhone. Can you try something like this? If the pass opens from Telegram there shouldn't be any problem.

@alexandercerutti Send the pass via telegram you means is the URL that serving the pass right?? Coz seems like telegram can't recognise .pkpass extension

**Comment by alexandercerutti** [comment]
@hhhlau You have to download it from Mac, send the `.pkpass` to your chat "saved messages" and then open it in Telegram from the iPhone. Telegram recognizes correctly the extension, trust me. If I cannot open the file from Telegram, the generated pass is broken somehow.

In that case, you should connect your iPhone through USB to your Mac and open Console.app, in `Applications/Utilities`,  check for iPhone logs on left and filter for "passkit". It will tell the exact problem, if any.

**Comment by hhhlau** [comment]
> @hhhlau You have to download it from Mac, send the `.pkpass` to your chat "saved messages" and then open it in Telegram from the iPhone. Telegram recognizes correctly the extension, trust me. If I cannot open the file from Telegram, the generated pass is broken somehow.
> 
> In that case, you should connect your iPhone through USB to your Mac and open Console.app, in `Applications/Utilities`, check for iPhone logs on left and filter for "passkit". It will tell the exact problem, if any.

@alexandercerutti you are right, I think there is something related the the pass itself..
I tried to obtain a sample pass from passkit.com and everything work prefect, download from url or sent from telegram. however, the generated one is not =(

I tried to unzipped both passes and I found the signature file are different, do this help indicating anything?
![Screenshot 2019-05-27 at 1 54 47 PM](https://user-images.githubusercontent.com/8468467/58398497-ce348700-8087-11e9-83a6-de25f2f439a7.png)

I will try to check the log on iPhone later today to see any finding

**Comment by alexandercerutti** [comment]
@hhhlau Well, I cannot understand anything by this 😊.

Let us know about the debug!

**Comment by hhhlau** [comment]
@alexandercerutti Debug seems clean with any finding..

The scene cap of Finder is trying to show one signature file is shown as "text file" while the one from pass kit is recognised as "UNIX executable". I don't know if this is related

**Comment by hhhlau** [comment]
I will check the certs again first, will update for any finding!

**Comment by alexandercerutti** [comment]
So here's the problem, but at this point what is weird is that Safari on Mac is able to render it. You should do also the same check with Console.app when opening on Mac.

**Comment by alexandercerutti** [comment]
@hhhlau you solved?

**Comment by hhhlau** [comment]
@alexandercerutti Hey Sorry for my late reply, I kinda fix the issue by re-generating all the certs again and it work just prefect now. But I have no clue why the issue only happens on iOS devices but not on MacOS...

**Comment by alexandercerutti** [comment]
@hhhlau It is weird in fact. I don't know.
Well, what is important is that you solved 😉
