### ISSUE TITLE
Cannot generate passes in parallel

### ISSUE THREAD

**Issue by ianbale** [alexandercerutti/passkit-generator#26]
Reference #25 

`fieldsArray.js` defined `fieldsKeys` outside of the `class`. This means they are shared across all class instances. 

Whilst the data is populated for a single instance, the static function `emptyUnique` clears this data for all instances.

The symptoms of this are that it is impossible to generate multiple passes in parallel (using promises).

**Comment by alexandercerutti** [comment]
About https://github.com/alexandercerutti/passkit-generator/issues/25#issuecomment-497679424,
I sadly cannot do that, as Apple says that pass keys but be unique in PASS Scope, not in field scope.

I have to look better at all the message to find a better solution.
The thing is really weird. Anyway I never tested parallel Pass generation.

**Comment by ianbale** [comment]
I see what you are saying...

I think you need another class that holds all fields and put it in there...

Was just working on a solution for a pull request.

Will do that at the same time.

**Comment by alexandercerutti** [comment]
I'll try this evening, in case, as I'm not able to do that right now. 👍 If you can find a better solutions, feel free to tell me that here and then open a PR.

**Comment by ianbale** [comment]
I've got a fix for this.

In a nutshell, I've added an extra class and put the fieldsList in there. That way I can have one instance per instance of pass, rather than it being shared across all passes. I've run some tests attempting to use duplicate keys which were noted in the debug output. 

It's in a local branch (issue-26-cannot-generate-passes-in-parallel), but I cannot push it.
A permission issue on the repository I guess? Only open to configured contributors?

**Comment by ianbale** [comment]
Not contributed to someone else's project before, so working this out as I go along... I think I should have done a fork rather than a branch... Will try that now.

**Comment by alexandercerutti** [comment]
Yeah, exactly

**Comment by ianbale** [comment]
That's done. You should have  a pull request now

**Comment by alexandercerutti** [comment]
I'll look at it asap 😉Thank you.
