### ISSUE TITLE
would be nice to use real dates

### ISSUE THREAD

**Issue by ianbale** [alexandercerutti/passkit-generator#29]
It would be nice if we could pass real dare objects for relevant date and expiry date rather than creating strings from date that just get parsed again before being reformatted.

This is hinted at in the docs which say: the type of the date value must be `String/date` which I read as string OR date, rather than "date string".

The docs also say:

> The date will be automatically parsed in order in the following formats:
> 
> MM-DD-YYYY hh:mm:ss,
> DD-MM-YYYY hh:mm:ss.
> 

I'm not sure this is a great idea... 

Without actually thinking it through, I took that as being able to use either format without specifying that format. Which if course, only partly works as expected.

If you use UK format (DD-MM) then if your date can only be parsed as a UK date (eg. 31-05) then it works as expected. However if your date can be parsed as a US date (MM-DD) as well, (eg. 01-05 1st May) then it gets parsed as a US date instead, so you end up with 5th January instead.

Far too easy to do some test with dates that parse as expected thinking it's all working ok, then hit a problem later when a wider range of dates are used. Using Date objects exclusively is the safer option.

Pull request to follow

**Comment by alexandercerutti** [comment]
As I commented in the Pull Request, it would bring a Breaking Change. Therefore I cannot accept the PR.
Anyway, I might consider integrating this in the forthcoming v2.

**Comment by ianbale** [comment]
Why would this be a breaking change since it's backwards compatible as you can still use the same date strings. You just have the option of using real dates as well....

**Comment by alexandercerutti** [comment]
Whops, my bad! I misread the changes! Yeah okay, it would not include a breaking change. But there is still the problem about tabs. Anyway, I'm going to re-open the PR. 😉

**Comment by ianbale** [comment]
tabs?

**Comment by alexandercerutti** [comment]
Yeah, Tabulations. I don't use spaces for the indentation in the code project and I don't want to mix them 😊

**Comment by ianbale** [comment]
Ah yes. I did not ice that despite it all lining up in my editor, Source Tree was showing it out of line... Did try copying you indent chars, but still didn't line up...

Indentation is very personal... Quite right to reject everyone else's tabs! ;-)

**Comment by alexandercerutti** [comment]
@ianbale Yeah, I know that is personal, in fact I'm using tabs 😂 I ask you to try to convert them or, for example disable while editing, the options about auto-fixing indentation. I had it in my VSCode at work for example
