### ISSUE TITLE
Can't update package files dynamically

### ISSUE THREAD

**Issue by GarettRogers** [alexandercerutti/passkit-generator#3]
It would be nice to have the ability to dynamically provide package content -- like image resources.

**Comment by alexandercerutti** [comment]
Hi!
I have thought about this feature, but not that sure how it could be used.

Can you provide me some examples?
And, also, what (for you) should be the fallback action (on fail)?

Thank you 😊

**Comment by alexandercerutti** [comment]
@GarettRogers I'm glad to tell you I've implemented your request in [v1.4.0](https://github.com/alexandercerutti/passkit-generator/commit/b68dfe0d8025a68b137cfc37c8b9f34a404c05e7).

I hope this is what you were looking for. 😊
