### ISSUE TITLE
Deploying script on Heroku not working

### ISSUE THREAD

**Issue by dwinc** [alexandercerutti/passkit-generator#34]
Hey there! I got my tweaked example version of your script working just fine locally.. very happy about that! But when I deploy on Heroku (for real world testing) I keep getting this error

Cannot GET /gen/examplePass

Any ideas?

**Comment by alexandercerutti** [comment]
Hi @dwinc!
I've never used Heroku, so I don't have many ideas about how to help you.
Have you checked ports?

**Comment by dwinc** [comment]
ah that's a shame. You have any cloud/server suggestions that would work "out of the box" that you know? Something with a free test account perhaps? Cheers

**Comment by alexandercerutti** [comment]
Sadly no... I'm sorry 😕

**Comment by alexandercerutti** [comment]
Doing some researches, I found that you cannot set ports on Heroku... so what I can suggest you to try is to deploy the examples with this value `process.env.PORT || 8080` as port on the webserver (if you already not doing that).

I found that answer here: https://stackoverflow.com/questions/28706180/setting-the-port-for-node-js-server-on-heroku

**Comment by dwinc** [comment]
Hey thanks for the support. It was indeed something with the port and something with static pages via express. Got it working now! Cheers! (now time to implement in the app!)

**Comment by alexandercerutti** [comment]
Awesome 😉
