### ISSUE TITLE
.pkpass file and ios simulator

### ISSUE THREAD

**Issue by GreenDano** [alexandercerutti/passkit-generator#35]
Hello, i'm having some troubles, the .pkpass file is generated correctly, but i'm using ios simulator to test, so, when i drag the file to simulator, doesn't show nothing :(

**Comment by alexandercerutti** [comment]
Hi @GreenDano!
Can you try to debug what's happening? I wrote in the Wiki [a "guide"](https://github.com/alexandercerutti/passkit-generator/wiki/Self-help) to debug. Let me know! 😉

**Comment by GreenDano** [comment]
Ok, I get from console:

"Invalid data error reading pass . The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.",

So, i need to check my certificates files, thank you! :D

**Comment by alexandercerutti** [comment]
You are welcome 😉 I'm keeping this open still for a while, so if you still need some help about this, you can ask here.

**Comment by ramyadavrp** [comment]
Can you please tell me how to open Console.app ?

**Comment by alexandercerutti** [comment]
Hey @ramyadavrp, Console.app is placed under `Applications/Utility/Console.app`.

**Comment by ramyadavrp** [comment]
> Hey @ramyadavrp, Console.app is placed under `Applications/Utility/Console.app`.

Thanks
does it need administration login?
Is this different from system.log?

**Comment by ramyadavrp** [comment]
> Hey @ramyadavrp I actually don't know if it requires administration login, but it might? If you discover it requires admin login, report it to me and I'll add it to wiki.
> Anyway I never heard of system.log. I looked for it and I saw you can see it from Console.app.

Yes, It's showing "You must authenticate as an Administrator to view messages"
And system.log exist in Log Reports.

**Comment by alexandercerutti** [comment]
@ramyadavrp Okay, this thing is new to me. Thank you. I'll add it to wiki asap.
Anyway, I don't know what you mean with LogReports. What I know is that Console.app let you inspect logs in real-time.

**Comment by ramyadavrp** [comment]
> @ramyadavrp Okay, this thing is new to me. Thank you. I'll add it to wiki asap.
> Anyway, I don't know what you mean with LogReports. What I know is that Console.app let you inspect logs in real-time.

If you don't mind can you please test my pass so i can be clear about the same.

**Comment by alexandercerutti** [comment]
Let's move this to another thread, otherwise we are going to flood GreenDeno with email notifications.

**Comment by ramyadavrp** [comment]
I have a last question-
Does pkpass generator website must by running on https ?
