### ISSUE TITLE
The pass could not be opened

### ISSUE THREAD

**Issue by kanyonbollinger** [alexandercerutti/passkit-generator#37]
This is more of a "what am I doing wrong" than an issue. I'm running this package on AWS lamdba and it works fine when I save the file to S3 (a typical filesystem). However when I use express, as the example has it, I get `The pass could not be opened`. 

Running express locally in the examples directory gives me the same error. It seems that express is manipulating the data. One other thing I tried is using Apple's signpass program to make sure my pass was valid and that worked.

When I can get the pass to work, simply changing the .pkpass to .zip works. However when I download the .pkpass file from express, Mac OS does not like it.
![screenshot 2019-07-14 at 8 43 57 PM](https://user-images.githubusercontent.com/3382683/61194710-22b3b600-a678-11e9-984e-7144ea8a24e5.jpg)

Let me know if I can provide any more additional information. Btw, thank you for making this! Once I get this working it will help me out a lot!

**Comment by alexandercerutti** [comment]
Hi @kanyonbollinger, let's find out!
Technically, Express *should* manipulate the response, as a Pass has *application/vnd.apple.pkpass* as mime type, even if it is a zip.

What can I ask you is to try to Debug what's going on!
Follow [this "guide"](https://github.com/alexandercerutti/passkit-generator/wiki/Self-help) and tell me if you find anything else. 😉

**Comment by kanyonbollinger** [comment]
Thanks for the quick response! Unfortunately Debug did not reveal anything. I tried downloading the pkpass file with Postman and a regular browser. And its not any problems with certificates/keys as Apple's signpass program works fine. Anything else you can think of?


```
examples kanyonbollinger$ node barcode.js 
Webserver started.
Barcode property is now: {
  message: 'Thank you for using this package <3',
  format: 'PKBarcodeFormatPDF417',
  messageEncoding: 'iso-8859-1'
}
Barcodes support is autocompleted: [
  {
    message: 'Thank you for using this package <3',
    format: 'PKBarcodeFormatQR',
    messageEncoding: 'iso-8859-1'
  },
  {
    message: 'Thank you for using this package <3',
    format: 'PKBarcodeFormatPDF417',
    messageEncoding: 'iso-8859-1'
  },
  {
    message: 'Thank you for using this package <3',
    format: 'PKBarcodeFormatAztec',
    messageEncoding: 'iso-8859-1'
  },
  {
    message: 'Thank you for using this package <3',
    format: 'PKBarcodeFormatCode128',
    messageEncoding: 'iso-8859-1'
  }
]
```
@alexandercerutti

**Comment by alexandercerutti** [comment]
I don't really know 🤔
Anyway, if you received "Pass could not be open", macOS' `Console.app` must have for sure printed out something in console.
Can you try again to obtain that error and debugging it through the second method of the guide above?

**Comment by alexandercerutti** [comment]
Hey there, @kanyonbollinger
were you able to solve?

**Comment by kanyonbollinger** [comment]
Yes I was able to solve. AWS was transforming some of the data. Thank you!

**Comment by alexandercerutti** [comment]
@kanyonbollinger Awesome! Would you like to be a bit more specific? Just for future reference 😊
