### ISSUE TITLE
[Thanks] Using it to create Gymcards

### ISSUE THREAD

**Issue by neogucky** [alexandercerutti/passkit-generator#39]
Hi Alex,

thanks for your node module! I used it to create a simple PWA to create digital membership cards to use in my local climbing gym, after I felt it was a pain to carry the physical card(s) with me all the time! 

I was surprised how well your module worked with firebase. Source of my PWA is open and maybe also helpful to others.

Repo: https://github.com/neogucky/membershipPassCard
Actual PWA: https://membershippasscard.firebaseapp.com/

**Comment by alexandercerutti** [comment]
I'm really happy to hear this ❤ Thank you for using it!
