### ISSUE TITLE
Row field in auxiliaryFields

### ISSUE THREAD

**Issue by alexandercerutti** [alexandercerutti/passkit-generator#41]
...

I noticed that in typedefinition for auxiliaryFields there is requirement of adding `row` property. I do not see anything about it in Apple docs. Moreover, if I add it I do not see auxiliaryFields on my pass.

_Originally posted by @aaliakseyenka in https://github.com/alexandercerutti/passkit-generator/pull/40#issuecomment-516790314_

**Comment by alexandercerutti** [comment]
`row` field is a "new" field that has been added recently, but there is no trace of it in the Apple Docs because, as I often said, those docs are not updated anymore (they are in the Archive for this reason).

I found that in one of the WWDC videos, maybe 2017 or 2016, I don't remember.
If I will have some time, I'll try to find it for you and link it here.
Anyway, it isn't that clear to me how it works.

**Comment by aaliakseyenka** [comment]
the thing is that if I use it( and I have to due to typescript). the fields do not show up at all

**Comment by alexandercerutti** [comment]
@aaliakseyenka Have you checked if Console.app tells you something about?
Anyway, isn't row optional or I do not remember correctly?

**Comment by aaliakseyenka** [comment]
it is mandatory. Will check the console, but the pass works, only the auxiliaryFields are missing.

**Comment by alexandercerutti** [comment]
Okay, yes, my bad! I have to release a fix with optional `row`, also for v2.0.0.
Or do you want to do that (just on `master`).

**Comment by aaliakseyenka** [comment]
not urgent for me.

**Comment by alexandercerutti** [comment]
Okay, so I'll do that this evening 👍

**Comment by alexandercerutti** [comment]
@aaliakseyenka I found the video where Apple explain how to use it:
https://developer.apple.com/videos/play/wwdc2018/720/?time=1143

**Comment by aaliakseyenka** [comment]
interesting, will test it more to check why content just disappeared

**Comment by alexandercerutti** [comment]
Okay, let me know! 👍
Anyway, I don't know if `row` this is already supported, even this is from WWDC 2018 🤔

**Comment by alexandercerutti** [comment]
@aaliakseyenka Released v1.6.8 with this edit. 😊🎉
