### ISSUE TITLE
Question: how to open/handle the pkpass file in my ionic cordova app?

### ISSUE THREAD

**Issue by dwinc** [alexandercerutti/passkit-generator#42]
Hi there, I got the entire Node js generate service to work. When calling the url and it generates the .pkpass file. On a desktop it just downloads the file, on Android too .. and with a pkpass file app it will open automatically. But somehow in my iOS app (built in ionic cordova), when calling the url it jumps into the safari browser opening the generate url, but then does not download / open the file. 
I've been searching the web for any answers on how to parse/handle the pkpass file in my ionic cordova project, but cannot find anything useful. Perhaps you have any thoughts? What should I be doing here?
Thanks!

**Comment by alexandercerutti** [comment]
Hi @dwinc
I don't know as I never used Ionic to build iOS apps. The only thing I know is that it uses Javascript.
I don't know how you are making the request to your server URL.
Does it use Node.JS, is it correct? I think you should use some kind of native (not Ionic) interface to get asynchronously the pkpass.

Let me know!

**Comment by dwinc** [comment]
So I got a cordova plugin to work which functions as a bridge between my project code (ionic/angular) and the native calls to download and open the pass. 
https://github.com/passslot/cordova-plugin-passbook

This works to an extend ..when I pass on the url to generate the pass .. nothing happens.. error returns NULL .. 
To test if the plugin worked, I downloaded a pass on my desktop, uploaded it somewhere, passed on the fixed url of the pkpass file in the code and then it worked. 

You have any idea why the download function wont accept the /gen/.. url as the pass file url?

Native function from the plugin that manages the download:

`- (void)downloadPass:(NSURL*) url headers:(NSDictionary * _Nullable)headers success:(AddPassResultBlock)successBlock error:(void (^)(NSError *error))errorBlock
{
    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url cachePolicy:NSURLRequestReloadIgnoringLocalCacheData timeoutInterval:20.0];
    // Fake User-Agent to be recognized as Passbook app, so that we directly get the pkpass file (when possible)
    [request addValue:@"Passbook/1.0 CFNetwork/672.0.2 Darwin/14.0.0" forHTTPHeaderField:@"User-Agent"];
    if( headers != nil ) {
        
        for (NSString* key in headers) {
            id value = headers[key];
            [request addValue:value forHTTPHeaderField:key];
        }
 
    }
    
    [NSURLConnection sendAsynchronousRequest:request queue:[NSOperationQueue mainQueue] completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
        [self tryAddPass:data success:successBlock error:errorBlock];
    }];
}`

**Comment by alexandercerutti** [comment]
I don't really know. It should work for me (I've no experience on this).
Which callback get called? Success or error?
Have you tried to check if the server gets actually called?

**Comment by alexandercerutti** [comment]
@dwinc have you solved the problem?

**Comment by dwinc** [comment]
Yes I was! Turns out the url had to be encoded properly as it had some special characters in it. So the issue was all mine. Thanks for responding so swiftly though. Appreciate it. App is going to be submitted today :)

**Comment by alexandercerutti** [comment]
You are welcome! I'm glad you solved. 😊

**Comment by janakan22** [comment]
@dwinc How did you install the plugin for your ionic app? Can you give me some tips on that. I am trying to open a pkpass file in my ionic app at the moment and I am failing miserably ...

**Comment by dwinc** [comment]
> @dwinc How did you install the plugin for your ionic app? Can you give me some tips on that. I am trying to open a pkpass file in my ionic app at the moment and I am failing miserably ...

This is a server side node js package. You don't need to add anything to your ionic app besides the URL to your server where this is hosting. I got it to work in the end but with help from a more experienced nodejs developer.

**Comment by janakan22** [comment]
maybe my question was a bit unclear ... @


> So I got a cordova plugin to work which functions as a bridge between my project code (ionic/angular) and the native calls to download and open the pass. https://github.com/passslot/cordova-plugin-passbook
> 
> This works to an extend ..when I pass on the url to generate the pass (Passbook.downloadPass('http://myurl.com/gen/examplePass').. nothing happens.. error returns NULL .. To test if the plugin worked, I downloaded a pass on my desktop, uploaded it somewhere, passed on the fixed url of the pkpass (Passbook.downloadPass('http://myurl.com/mypass.pkpass) file in the code and then it worked.
> 
> You have any idea why the download function wont accept the /gen/.. url as the pass file url?
> 
> Native function from the plugin that manages the download:
> 
> ```objc
> - (void)downloadPass:(NSURL*) url headers:(NSDictionary * _Nullable)headers success:(AddPassResultBlock)successBlock error:(void (^)(NSError *error))errorBlock
> {
>     NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url cachePolicy:NSURLRequestReloadIgnoringLocalCacheData timeoutInterval:20.0];
>     // Fake User-Agent to be recognized as Passbook app, so that we directly get the pkpass file (when possible)
>     [request addValue:@"Passbook/1.0 CFNetwork/672.0.2 Darwin/14.0.0" forHTTPHeaderField:@"User-Agent"];
>     if( headers != nil ) {
>         for (NSString* key in headers) {
>             id value = headers[key];
>             [request addValue:value forHTTPHeaderField:key];
>         }
>     }
>    
>     [NSURLConnection sendAsynchronousRequest:request queue:[NSOperationQueue mainQueue] completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
>         [self tryAddPass:data success:successBlock error:errorBlock];
>     }];
> }
> ```


maybe my question was a bit unclear. How did you manage to display the generated pass in the Ionic App using the Cordova plugin mentioned in your answer above. (https://github.com/passslot/cordova-plugin-passbook)
