### ISSUE TITLE
Dynamic images

### ISSUE THREAD

**Issue by palancana** [alexandercerutti/passkit-generator#43]
Hi @alexandercerutti! 
First of all, thank you for your hard work on this package, it is just awesome! 

I'm in a situation where the thumbnail image has to be loaded dynamically, because it is the image of the person that has the card. I saw that on previous versions there was a `.load` function that downloaded an image resource. 

Is there any substitution for this now? Could you attach an example in that case?

Thank you!

**Comment by alexandercerutti** [comment]
Hi.@palancana, thank you very much!
Of course there's an alternative to add files dynamically.

Factory function `createPass` [accepts three parameters](https://github.com/alexandercerutti/passkit-generator/blob/master/API.md#pass_class_constructor): look at ‘additionalBuffers`, which is the second parameter 😉

It will allow you to load Buffers in the pass

**Comment by palancana** [comment]
Thank you so much @alexandercerutti! The [Migration Guide](https://github.com/alexandercerutti/passkit-generator/wiki/Migrating-from-v1-to-v2) explains everything. I was looking into the examples folder and I couldn't find an example, that's why I was confused. Maybe we could add another example to the folder that uses `additionalBuffers`.

I'm gonna close the issue, and in case somebody comes here and wants to see a chunk of code, this is what I did, taking into account that the `userPhoto` is coming in Base64 format.

```Javascript
let pass = await createPass({
  model: './pass-models/my-pass',
  certificates: {
    wwdr: './certs/AppleWWDRCA.pem',
    signerCert: './certs/signerCert.pem',
    signerKey: {
      keyFile: './certs/signerKey.pem',
      passphrase: 'my-password'
    }
  },
  overrides: {
    serialNumber: '123456789'
  }
}, {
  'thumbnail@3x.png': Buffer.from(userPhoto, 'base64')
})
```

**Comment by alexandercerutti** [comment]
Yeah, I agree, it could be useful. 😊
Do you mind to leave a star to the project? ⭐️ It would be really appreciated!

**Comment by alexandercerutti** [comment]
I've added the [example](https://github.com/alexandercerutti/passkit-generator/blob/master/examples/additionalBuffers.ts)! Let me know what you think about 😉

**Comment by palancana** [comment]
Starred! The example is super nice! Awesome job on this project @alexandercerutti!! 👌🏻
