### ISSUE TITLE
Allow characters such as dashes and dots in authenticationToken

### ISSUE THREAD

**Issue by ozcanturkmen** [alexandercerutti/passkit-generator#45]
In current implementation only alphanumerical characters and underscores are allowed in authenticationToken field of a pass, as far as I understand. Is it possible to allow some other characters such as dashes, dots, slashes, and plus signs? Those are fairly common because of  base64 and base64url encodings, and JWT tokens. Moreover, in Apple's PassKit I think there is no restriction on authenticationToken except being a string. Thanks for providing this useful library, thank you for your time and efforts.

**Comment by alexandercerutti** [comment]
@ozcanturkmen Hey! Thanks to you for using it! 😉
Yes, of course, I think there wouldn't be any problems.
We just have to change that field's signature for Joi.

I'll make some tests in the next hours/days and test it against JWT and base64.
I will also provide you some instructions to test it with me if you agree, because actually I'm not that familiar with JWT 😅😂

Anyway the only restriction for authentication token is minimum length of 16 characters 😊

**Comment by ozcanturkmen** [comment]
@alexandercerutti  I'm glad to hear that we can fix this without much effort, since I am currently trying to use JWT as authentication token with the library :) And of course, I'd gladly help with testing. Thanks in advance!

**Comment by alexandercerutti** [comment]
It should be enough removing `.token()` from line 25 in schema.js. I'm going to test this, can you too? 😊

**Comment by ozcanturkmen** [comment]
Sure thing! I confirm that this change made a 316 chars long JWT token pass the validation 😊

**Comment by alexandercerutti** [comment]
Woah, I never expected a 316 chars long authenticationToken to be used 😂
Anyway, I tested it too and it works.
I think I might release a new version right now if you agree and you don't have other ideas/requests.

**Comment by ozcanturkmen** [comment]
Nope, I think that's enough for now. Please release the new version so that I can start using it immediately 😊Thank you, much appreciated!

**Comment by alexandercerutti** [comment]
Done @ozcanturkmen, published in 2.0.1 😊
Can I ask you to leave a star 🌟 on the project? It is really important to me! Thank you very much 😊

**Comment by ozcanturkmen** [comment]
Sure thing! 😉Thank you very much, we can close the issue now.
