### ISSUE TITLE
index.d.ts:67 and 74 have bad parameter types

### ISSUE THREAD

**Issue by nuts-n-bits** [alexandercerutti/passkit-generator#47]
line 67: `beacons(...data: Schema.Beacon[] | null): this`
line 74: `locations(...data: Schema.Location[] | null): this`

TSC complains, rightfully, that a rest parameter must be of array type. This seems fixable just by removing the `| null` part.

the commit I'm referencing to is 681d9d144d9246440529b113e4e15a869a2df32d.

BTW, thanks for writing this library :]

**Comment by alexandercerutti** [comment]
@nuts-n-bits Hi, thank you for using it 😊
I received another report about this (I'll link it here later). It seems to be a problem related to some of strict-checking flags of tsconfig on implementer side. Have you tried to remove them?

The fact is that I never inserted strict-checking options, so if I do it right now, I could fix if and remove | null, but I'm afraid the reset mode could break in terms of typescript syntax checking.

**Comment by nuts-n-bits** [comment]
I guess there are situations where you pass into these functions `beacons(null)` to signal a reset?

If that's the case can we get a function overload to get the types right? I am thinking this:

```
beacon(...data : Schema.Beacon[]) : this;
beacon(null) : this;
beacon(...vararg : (Schema.Beacon|null)[]) { // implementation, except that
      // checking vararg[0] === null replaces data === null
```

If you don't mind I can patch and PR.

**Comment by alexandercerutti** [comment]
Okay, I think you are right! Let's talk about this in the PR topic 😊
