### ISSUE TITLE
Adding pkpass file from barcode example does not work

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [alexandercerutti/passkit-generator#54]
I tried to add the downloaded file from the barcode example and send it via email.
This actually did not work - the file is recognized as Apple wallet file but if I press on it nothing happens. Same when I download the file and try to open it via iCloud. 
Any idea? Does this work for you?

**Comment by alexandercerutti** [comment]
Hey there mariomurrent-softwaresolutions ! Thanks for using Passkit-generator! 😊

If you cannot open it, it is probably a not valid pass.
Recognition is based on file extension, so you cannot determine if it is valid by how it's file is shown.
If you are on or have a Mac, what I can suggest you is to debug it by following the guide I created in the wiki (I'll attach the link once I'll be in front of the PC).

Let me know 😉

**Comment by mariomurrent-softwaresolutions** [comment]
Hi,
Hmm, well debugging is enabled, and there are no errors - If I open the URL localhost:8080/gen/examplePass the side just closes on my iPhone :( So seems nothing to happen

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, sorry my fault - actually I did not see the typo in the teamID - and the generator is not complaining about this :P ..

**Comment by alexandercerutti** [comment]
Glad you solved! 😄
How was you typo? I mean, you just misspelled it or wrote the dotted notation wrong?

**Comment by mariomurrent-softwaresolutions** [comment]
I just misspelled one letter, because I did not copy it ... That was the problem

**Comment by alexandercerutti** [comment]
Okay, well, to make PG complain about it, I should make a check against the certificate, but I think it is a bit excessive to do 😊 in fact this already happens when you open it
