### ISSUE TITLE
Passes not showing within apple wallet

### ISSUE THREAD

**Issue by btemrk** [alexandercerutti/passkit-generator#56]
Hi,
I've ran into a problem trying to add passes to apple wallet.
I'm able to successfully generate a pass(.pkpass file). I can double click on the file and it displays in the Pass Viewer app.
The issue i'm having is that when I try to add it to apple wallet via Simulator (it hangs - nothing happens) or Iphone (pass error - invalid pass). Not sure if you've ran into this issue before, but any help will be appreciated. 

Side Note: I'm able to manually create a pass following Apple Doc [Building Your First Pass
](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/YourFirst.html).

I am using the generic sample pass - The only thing I've change is the   "passTypeIdentifier" & "teamIdentifier"
Any help will be much appreciated - I have to admit, this is the first time i'm developing anything regarding Apple ecosystem.

my pass.json file: 

"formatVersion" : 1,
  "passTypeIdentifier" : "pass.com.testwallet",
  "serialNumber" : "8j23fm3",
  "webServiceURL" : "https://example.com/passes/",
  "authenticationToken" : "vxwxd7J8AlNNFPS8k0a0FfUFtq0ewzFdc",
  "teamIdentifier" : "PLACEHOLDER",
  "locations" : [
    {
      "longitude" : -122.3748889,
      "latitude" : 37.6189722
    },
    {
      "longitude" : -122.03118,
      "latitude" : 37.33182
    }
  ],
  "barcode" : {
    "message" : "123456789",
    "format" : "PKBarcodeFormatPDF417",
    "messageEncoding" : "iso-8859-1"
  },
  "organizationName" : "Toy Town",
  "description" : "Toy Town Membership",
  "logoText" : "Toy Town",
  "foregroundColor" : "rgb(255, 255, 255)",
  "backgroundColor" : "rgb(197, 31, 31)",
  "generic" : {
    "primaryFields" : [
      {
        "key" : "member",
        "value" : "Johnny Appleseed"
      }
    ],
    "secondaryFields" : [
      {
        "key" : "subtitle",
        "label" : "MEMBER SINCE",
        "value" : "2012"
      }
    ],
    "auxiliaryFields" : [
      {
        "key" : "level",
        "label" : "LEVEL",
        "value" : "Platinum"
      },
      {
        "key" : "favorite",
        "label" : "FAVORITE TOY",
        "value" : "Bucky Ball Magnets",
        "textAlignment" : "PKTextAlignmentRight"
      }
    ],
    "backFields" : [
      {
        "numberStyle" : "PKNumberStyleSpellOut",
        "label" : "spelled out",
        "key" : "numberStyle",
        "value" : 200
      },
      {
        "label" : "in Reals",
        "key" : "currency",
        "value" : 200,
        "currencyCode" : "BRL"
      },
      {
        "dateStyle" : "PKDateStyleFull",
        "label" : "full date",
        "key" : "dateFull",
        "value" : "1980-05-07T10:00-05:00"
      },
      {
        "label" : "full time",
        "key" : "timeFull",
        "value" : "1980-05-07T10:00-05:00",
        "timeStyle" : "PKDateStyleFull"
      },
      {
        "dateStyle" : "PKDateStyleShort",
        "label" : "short date and time",
        "key" : "dateTime",
        "value" : "1980-05-07T10:00-05:00",
        "timeStyle" : "PKDateStyleShort"
      },
      {
        "dateStyle" : "PKDateStyleShort",
        "label" : "relative date",
        "key" : "relStyle",
        "value" : "2013-04-24T10:00-05:00",
        "isRelative" : true
      }
    ]
  }
}

Code I'm Using:
	try {
		const examplePass = await createPass({
			model: "./testwallet",
			certificates: {
				wwdr: "./certs/wwdr.pem",
				signerCert: "./certs/signerCert.pem",
				signerKey: {
					keyFile: "./certs/signerKey.pem",
					passphrase: "PlaceHolder"
				}
           },
			/* overrides: {
				// keys to be added or overridden
				serialNumber: "AAGH44625236dddaffbda"
			} */
		});
	
	     //Adding some settings to be written inside pass.json
		//examplePass.localize("en", { ... });
		//examplePass.barcode("36478105430"); // Random value 
	 
		// Generate the stream, which gets returned through a Promise
		 var stream = examplePass.generate();
		
		 // Create a write stream to a file
		pkpass = fs.createWriteStream('genCardTest.pkpass');

		stream.pipe(pkpass);
	
		doSomethingWithTheStream(stream);
	} catch (err) {
		doSomethingWithTheError(err);
	}

**Comment by btemrk** [comment]
Thank you in advance, I figured it out. I was using the wrong WWDR from [Apple PKI](https://www.apple.com/certificateauthority/)

**Comment by alexandercerutti** [comment]
@btemrk Hey there! Glad you solved!
Sorry if I didn't respond to you in time but it was nighttime where I am when you wrote 😄

**Comment by GazEdge** [comment]
> Thank you in advance, I figured it out. I was using the wrong WWDR from [Apple PKI](https://www.apple.com/certificateauthority/)

Ive also run into the same issue. Worked out that the WWDR expiring in 2030 wont work on iOS, but the certificate expiring in 2023 does work. Does anyone know if this is a known issue on iOS? I feel the reason must simply be because WWDR expiring 2030 has not been included in iOS - are there any tech notes to confirm this?
