### ISSUE TITLE
Coupon Card

### ISSUE THREAD

**Issue by onlyamir007** [alexandercerutti/passkit-generator#57]
First of all, thank you for your hard work on this package, it is just awesome!

Im trying to create coupon card how can i do it?
I have **strip@2x.png** image it is not pickup up.
im missing something ? in documentation i did not find anything. 

Thank you

**Comment by alexandercerutti** [comment]
Hey there, @onlyamir007! Thank you for using pg! 😄

Mmm so if you try to rename the resulting zip file from `.pkpass` to `.zip` and unzip it, you don't see the file in both the bundle and manifest.json or you cannot just make it visible in your resulting pass?

Let me know!

**Comment by onlyamir007** [comment]
thanks for quick response... 
yes i did unzip file i can see all files there & manifest.json file screen you can check.
![Capture](https://user-images.githubusercontent.com/13790963/94283849-6950a180-ff06-11ea-96ac-a0ad020e616d.JPG)

**Comment by alexandercerutti** [comment]
@onlyamir007 for what I see from your screenshots, what you are trying to create is a `boardingPass`, not a `coupon` 😊.
Of course, boardingPasses do not support strip images.

Refer to [this table](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html) to understand which files are supported on each type.

![image](https://user-images.githubusercontent.com/5442545/94288722-07b92300-ff58-11ea-83b0-afb3256dd976.png)

**Comment by onlyamir007** [comment]
got it ... thank you
