### ISSUE TITLE
Error: Cannot read public key. OID is not RSA.

### ISSUE THREAD

**Issue by marcelocecin** [alexandercerutti/passkit-generator#6]
hi there
after executing the commands:
`$ openssl pkcs12 -in <cert-name>.p12 -clcerts -nokeys -out signerCert.pem -passin pass:<your-password>`
`$ openssl pkcs12 -in <cert-name>.p12 -nocerts -out signerKey.pem -passin pass:<your-password> -passout pass:<secret-passphrase>`
`node barcode.js`
I'm getting the error:
Error: Error: Cannot read public key. OID is not RSA. at _parseCertificates.then.catch (/Users/marcelocecin/node_modules/passkit-generator/src/pass.js:64:11)

**Comment by alexandercerutti** [comment]
Hi!
This error might be a bit tough to investigate on.
Can you please provide me more details, like your certificates? If you don't trust to put them openly here, you can zip them with a password and send me the password on Twitter at @AlexandrCerutti or Telegram (https://t.me/AlexandrCerutti).

Anyway, I'm going to do some researches meanwhile to understand the origin of that error.

Thank you for the collaboration.

**Comment by marcelocecin** [comment]
hi
I'm using the wrong WWDR.pem
so I downloaded the right one at [
https://developer.apple.com/certificationauthority/AppleWWDRCA.cer](https://developer.apple.com/certificationauthority/AppleWWDRCA.cer)
thank you

**Comment by alexandercerutti** [comment]
Glad you solved 😊 I bet you downloaded the expired wwdr certificate, right? 😉
