### ISSUE TITLE
Set Relevance maxDistance?

### ISSUE THREAD

**Issue by nicdichiara** [alexandercerutti/passkit-generator#60]
Hi - Thank you so much for this repo. I was happy to support your great work. 

I am using locations in my implementation, but cannot find in the docs of this repo where to add the maxDistance for locations value? 

Any help would be appreciated! Thanks!

**Comment by alexandercerutti** [comment]
Hey there, @nicdichiara, thank you for using it!

What you are looking for, can be found here: https://github.com/alexandercerutti/passkit-generator/blob/master/API.md#pass_class_constructor

In the factory method, you can pass `options.overrides`, in which you can set every "sparse" key that does not have a method or not requires some kind of elaboration.

I also was going to link you the typescript typings but I saw right now that when I created them, I left them too generic in terms of types. This has to be corrected on the next release (when it will happen, if not a problem; right now I'm working on another big big big project that concerns Apple Passes creation!).

Hope this helps you! Let me know! 😉

**Comment by alexandercerutti** [comment]
I've released v2.0.6 with dependencies update and automated types export.

https://github.com/alexandercerutti/passkit-generator/blob/master/src/schema.ts#L79

Thanks for using passkit-generator! 😊
