### ISSUE TITLE
Extracting key and cert from pkcs12

### ISSUE THREAD

**Issue by lochiamavanoK** [alexandercerutti/passkit-generator#62]
Hi Alexander,
first of all let me say what an extraordinary and well documented job you and code contributors have done here!

I'm writing because while compiling I'm having some issue with pem file creation:
`wwdr.pem` - created by exporting from key chain (no problem) 
`thenameofmyfile.p12` - created by exporting from key chain the pass.cer downloaded from apple dev site (no problem)
now I'm using `thenameofmyfile.p12` to create the `signerCert.pem` and the `signerKey.pem` using the command as in the readme document:

```
# Extracting key and cert from pkcs12
$ openssl pkcs12 -in thenameofmyfile.p12 -clcerts -nokeys -out signerCert.pem -passin pass:mypassword
$ openssl pkcs12 -in thenameofmyfile.p12 -nocerts -out signerKey.pem -passin pass:mypassword -passout pass:mypasspassphrase
```

now the two file are correctly created but the signerCert.pem is working and signerKey.pem is like it's empty

and obviously trying to compile running the command rpm run test I receive the error below

```
Error: Something went really bad in the pass initialization! Look at the log below this message. It should contain all the infos about the problem: 
Error: Invalid certificate(s) loaded: signerKey. Please provide valid WWDR certificates and developer signer certificate and key (with passphrase).
    Refer to docs to obtain them.
```

any idea on what I'm doing wrong?

**Comment by alexandercerutti** [comment]
Hey there, @lochiamavanoK! Thank you and thank you for using it! 😊

Okay so, I'm not really sure what could be the issue here. Also, I must say that that wasn't the easiest part of the whole project. I'm not that into signature creation and cyphering.

So you confirm that the weight of `signerKey.pem` is 0KBs? If should be at least few KBs.

May I ask you to do follow the whole steps from scratch also by trying the only-terminal steps?

Let me know!

**Comment by lochiamavanoK** [comment]
Hi Alexander,
no, the file written was not at 0kb, but empty (as a certificate), the system was unable to read it because of some evident exporting problem.

following your suggestion and doing it from scratch using terminal as explained in Non-macOS-steps has worked

**Comment by alexandercerutti** [comment]
Okay, so this seems to have been solved... but you can repeat the problem with MacOS Keychain Access?

**Comment by lochiamavanoK** [comment]
Hi Alexander,
trying form scratch using the method explained in the readme file and unfortunately it doesn't work as expected (maybe is related to my os version), but there are some discrepancy.

As I can see, there is a missing part where you need to generate the .key file (necessary to correctly create the other file).

In any case I suggest a mixed procedure.

first part as listed in the readme file
second part as listed in the non Mac file

in my experience is the easiest and fastest

**Comment by alexandercerutti** [comment]
I never heard of anyone having problems with this.
Which version of macOS are you working on?

Anyway, the first three steps are the same, so I don't understand which is the first part and the second part for you.

The `.key` generation procedure happens at point 6 in Readme, with the second command, and at point 6 in non-macOS-steps.md.

The steps are quite different. Readme's relies on PKCS12 format (`.p12`) to have both certificate and key in the same file.

**Comment by lochiamavanoK** [comment]
Hi Alexander,
my fault, the problem was related to permission on folders, now is working perfectly.

thanks a lot

**Comment by alexandercerutti** [comment]
Great to hear and to know! 👍
