### ISSUE TITLE
node-forge - dependency update needed

### ISSUE THREAD

**Issue by ianbale** [alexandercerutti/passkit-generator#63]
**npm audit** reports a high priority issue with node-forge (one of your dependencies).

> High          │ Prototype Pollution in node-forge
> Package       │ node-forge
> Patched in    │ >= 0.10.0
> Dependency of │ passkit-generator
> Path          │ passkit-generator > node-forge
> More info     │ https://npmjs.com/advisories/1561

Could you update and deploy a new version please?

**Comment by alexandercerutti** [comment]
Hi @ianbale
Yes, I saw the notice but never had the time. I'll do that as soon as possibile.

**Comment by alexandercerutti** [comment]
Hey @ianbale,
I've released v2.0.6 right now with the dependencies update and a lot more!
Enjoy 😄
