### ISSUE TITLE
Does pkpass generator website must by running on https ?

### ISSUE THREAD

**Issue by alexandercerutti** [alexandercerutti/passkit-generator#70]
I have a last question-
Does pkpass generator website must by running on https ?

_Originally posted by @ramyadavrp in https://github.com/alexandercerutti/passkit-generator/issues/35#issuecomment-795319762_

**Comment by alexandercerutti** [comment]
@ramyadavrp You mean the url in `webServiceUrl`?

**Comment by ramyadavrp** [comment]
> @ramyadavrp You mean the url in `webServiceUrl`?

yes, actually i am creating pkpass from my laravel website, which is running on http not on https.

Currently i am able to see pkpass view on browser and pass viewer but not able to add in wallet, even not getting any error in log.
