### ISSUE TITLE
Cannot find module 'passkit-generator'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

### ISSUE THREAD

**Issue by jtuttas** [alexandercerutti/passkit-generator#74]
Dear Alexander,
just try to set up you passkit-generator but I always get the above Error (Cannot find module 'passkit-generator'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?), even with your example in the README.md File

```
import { createPass, Pass } from "passkit-generator";

import path from "path";

import { createWriteStream } from "fs";

```

Did you have any idea, what the problem might be?

best regards

jtuttas

**Comment by alexandercerutti** [comment]
Hi @jtuttas, I guess you solved and I guess it might have been an issue with your Typescript configuration, isn't it? Which was the issue?

I didn't even had time to answer you in time 😂
Glad you solved.
