### ISSUE TITLE
webServiceURL can't be overridden

### ISSUE THREAD

**Issue by teawithfruit** [alexandercerutti/passkit-generator#8]
Hello.

Thanks for this cool package!
Is it a bug or a feature, that it is not possible to ```webServiceURL``` overridden?

Thanks

**Comment by teawithfruit** [comment]
Sure.
```
{
  "formatVersion": 1,
  "passTypeIdentifier": "pass.net.test.ticket",
  "serialNumber": "jd3bb6611a17ced10d84631b6782f367",
  "teamIdentifier": "ABCDEFGHI",
  "webServiceURL": "",
  "authenticationToken": "fb9c32b79ff1a537cb93891cbda3eea7",
  "relevantDate": "2019-11-13T00:00:00+00:00",
  "locations": [
    {
      "longitude": -122.3748889,
      "latitude": 37.6189722
    },
    {
      "longitude": -122.03118,
      "latitude": 37.33182
    }
  ],
  "organizationName": "Test",
  "description": "Ticket",
  "foregroundColor": "rgb(255, 255, 255)",
  "backgroundColor": "rgb(60, 65, 76)",
  "eventTicket": {
    "primaryFields": [
      {
        "key": "event",
        "label": "EVENT",
        "value": "Test"
      }
    ],
    "secondaryFields": [
      {
        "key": "loc",
        "label": "LOCATION",
        "value": "Test"
      }
    ],
    "transitType": ""
  },
  "barcode": {
    "message": "https://test.local.de/fb9c32b79ff1a537cb93891cbda3eea7",
    "format": "PKBarcodeFormatQR",
    "messageEncoding": "iso-8859-1"
  },
  "barcodes": [
    {
      "message": "https://test.local.de/fb9c32b79ff1a537cb93891cbda3eea7",
      "format": "PKBarcodeFormatQR",
      "messageEncoding": "iso-8859-1"
    }
  ]
}
```
Unfortunately the ```webServiceURL``` field is empty.

**Comment by alexandercerutti** [comment]
Are you sure `url` variable you are putting in overrides has content? Just to not exclude anything.
I'll investigate asap. There may be problems with schema validation.

**Comment by teawithfruit** [comment]
Yes, I'm sure.
I've checked it a minute ago.

Thank you for your very quick response!

**Comment by alexandercerutti** [comment]
Okay! I'll try to investigate this evening (GMT+1).

**Comment by alexandercerutti** [comment]
Have you tried to execute the `node` process with the flag `DEBUG=*`? It may give us more informations about the problem. Let me know.

**Comment by alexandercerutti** [comment]
I had a moment and tried to execute a fast test. webServiceURL failed the regex validation and got this error:

```
Schema validation failed due to error: child "webServiceURL" fails because ["webServiceURL" with value "https://google.com" fails to match the required pattern: /^https?:\/\/(?:[a-z0-9]+\.[a-z0-9]+\.[a-z]+(?:\.[a-z]+)?|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\/?(?:[a-z\/_%0-9A-Z.]+)?/]
```

I have to understand this regex put inside there or what to fix.

**Comment by alexandercerutti** [comment]
I created a new regex:
`https?:\/\/(?:(?:[a-z0-9]+\.?)+\/?)+`

Can you please try to replace the current regex in your local `schema.js`, as below, and test again if it works?

```javascript
webServiceURL: Joi.string().regex(/https?:\/\/(?:(?:[a-z0-9]+\.?)+\/?)+/),
```

**Comment by teawithfruit** [comment]
Thank's again for your quick response.
I did a bit more debugging and I found out, that ```webServiceURL``` do not pass if ```authenticationToken``` is set inside the schema file. If I remove the following lines, it also works with the old ```webServiceURL``` regex.
```
authenticationToken: Joi.string().token().min(16).when("webServiceURL", {
  is: Joi.exist(),
  then: Joi.required()
}),
```

**Comment by alexandercerutti** [comment]
Okay @teawithfruit, I've pushed to a new branch [bugfix](https://github.com/alexandercerutti/passkit-generator/tree/bugfix). Try with this version and let me know 👍

**Comment by alexandercerutti** [comment]
Hi @teawithfruit, any news?

**Comment by teawithfruit** [comment]
Sorry for the late response. Yes, I've tested it and it's working now. Thank you!

**Comment by alexandercerutti** [comment]
Awesome! I'm going to push this update on NPM asap 😊

Closing!
