### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by HammadUllahKhan12** [alexandercerutti/passkit-generator#80]
const stream = await examplePass.generate()
   generate the complete object but i need .pkpass. any help or guide 
   
   response :: 
   
![image](https://user-images.githubusercontent.com/48718737/131848167-2fc4fb34-54a9-4da3-b79c-1a9a8b034fe8.png)

**Comment by alexandercerutti** [comment]
`examplePass.generate()` is not asynchronous. It returns a stream. You should pipe it to a write stream or network response or convert it to a buffer.

**Comment by alexandercerutti** [comment]
Look at examples folder

**Comment by HammadUllahKhan12** [comment]
yes @alexandercerutti I saw the example I was in GQL but it was present in express response. Do we have any function ? 
![image](https://user-images.githubusercontent.com/48718737/131850340-2e59c8c0-9f5e-4334-b968-c52ea4476055.png)

**Comment by alexandercerutti** [comment]
What's GQL? It is not clear to me what you are asking anyway.
Moreover, awaiting `examplePass.generate()` belongs to the old version (v1).

**Comment by HammadUllahKhan12** [comment]
@alexandercerutti GQL means graph query language. I just want return the .pkpass file of my pass.

**Comment by HammadUllahKhan12** [comment]
but in example it set the .pkpass in response.

![image](https://user-images.githubusercontent.com/48718737/131851713-8a77cbd6-ae70-4e46-bb92-aa6c813ad6d3.png)

**Comment by HammadUllahKhan12** [comment]
yes @alexandercerutti i read it but cannot able to get without response.set.

**Comment by alexandercerutti** [comment]
@HammadUllahKhan12 excuse me, what?
Please, explain clearly what you want to achieve, because it is not clear at all. How you started this conversation also doesn't help.

You want to save the `.pkpass` file on the file system? You have to use `fs.createWriteStream()` I guess.
You want to get the `.pkpass` file as buffer? You have to convert it.

Let me know

**Comment by alexandercerutti** [comment]
Hey @HammadUllahKhan12, were you able to solve?
