### ISSUE TITLE
Need Help regarding the wallet pass file

### ISSUE THREAD

**Issue by shubhamrmob** [alexandercerutti/passkit-generator#81]
I have tried creating a wallet pass using this library and I can open that pkpass file in my mac and it works.
But when i try to open that in my i-phone it doesn't works.
I tried sending it to my mail on phone and then while downloading the pkpass nothing happens and in safari it says safari can not download this file. This is my pass.json file and i have also attached the pkpass file generated using this library.
I tried this on Iphone 8 and Iphone X and Iphone 12 pro max. File is easily openable in Macbook pro but not in Iphone.
I have verifies the team identifier and pass type identifier these are all correct.
[Pkpass file drive link](https://drive.google.com/file/d/11KK7CDyY3wr87D650sAINg0p9zr-JVoh/view?usp=sharingl)

```json
{
	"formatVersion": 1,
	"passTypeIdentifier": "pass.com.mXXXXc.beXXXtac",
	"serialNumber": "23nmyuxofg146na",
	"teamIdentifier": "44VXXXY3TF",
	"barcodes": [
		{
			"message": "123456789",
			"format": "PKBarcodeFormatQR",
			"messageEncoding": "iso-8859-1"
		}
	],
	"barcode": {
		"message": "123456789",
		"format": "PKBarcodeFormatQR",
		"messageEncoding": "iso-8859-1"
	},
	"organizationName": "Github Inc.",
	"description": "A Booking pass",
	"foregroundColor": "rgb(255, 255, 255)",
	"backgroundColor": "rgb(253, 123, 35)",
	"coupon": {}
}
```

**Comment by alexandercerutti** [comment]
Hey there @shubhamrmob, thanks for using passkit-generator!

I recently heard of another case that might be the same as yours: Macs have different files requirements than iPhones. You probably don't have the right files inside your bundle.

What I can suggest you is to look at issue #79 and let me know if you are able to solve 👍

**Comment by shubhamrmob** [comment]
Thanks @alexandercerutti . Let me check

**Comment by shubhamrmob** [comment]
@alexandercerutti  I tried adding icon@3x.png , but it didn't worked. 
My team mate has created .pem files in his machine and shared that pem files with me and I am using those files. Will that be a reason for this issue ?

**Comment by alexandercerutti** [comment]
@shubhamrmob I actually don't know if that can be an issue. What I can suggest you is to follow the [debug guide i wrote in wiki](https://github.com/alexandercerutti/passkit-generator/wiki/Self-help).

Also, Apple wrote a list of common problems you might incur into: https://developer.apple.com/documentation/walletpasses/building_a_pass#3732528

Let me know if this helped.

**Comment by alexandercerutti** [comment]
Hey @shubhamrmob, have you been able to solve it? If so, which was the issue?

**Comment by shubhamrmob** [comment]
I replaced the Apple WWDR certificate and its started working. The certificate was not even expired so this was really weird.
Thanks for your help @alexandercerutti
