### ISSUE TITLE
Issue running "folder model" example - "await is only valid in async function"

### ISSUE THREAD

**Issue by HarryHendel** [alexandercerutti/passkit-generator#83]
Hello,

I am trying to work out how to use PassKit generator, but I'm running into an issue. When I try to run the "folder model" example I get the error "await is only valid in async function" in reference to the line where the const examplePass is defined:

```typescript
const { createPass } = require("passkit-generator");

	const examplePass = await createPass({
		model: "./passModels/myFirstModel",
		certificates: {
			wwdr: "./certs/wwdr.pem",
			signerCert: "./certs/signercert.pem",
			signerKey: {
				keyFile: "./certs/signerkey.pem",
				passphrase: "0410Harry"
			}
		},
		overrides: {
			// keys to be added or overridden
			serialNumber: "1"
		}
	});

	// Adding some settings to be written inside pass.json

	examplePass.barcode("1"); // Random value

	// Generate the stream .pkpass file stream
	const stream: Stream = examplePass.generate();
```

Thanks in advance!

**Comment by alexandercerutti** [comment]
Hi @HarryHendel, thanks for using passkit-generator! I guess you are missing the base concept of async-await. You should check if your environment (node version) supports top-level await or you are running in an async function.

Let me know!

**Comment by alexandercerutti** [comment]
@HarryHendel I didn't see the other error. Are you running in a Typescript project?

**Comment by HarryHendel** [comment]
Ok I'm kinda stuck. All I want is to generate a pass, so how do I eliminate that "await only valid in async function" error? (I have added back the "await")
