### ISSUE TITLE
I have tried this and it just fails.

### ISSUE THREAD

**Issue by alexandercerutti** [alexandercerutti/passkit-generator#84]
I have tried this and it just fails.
is there an example?
my certificates object contains a string version of the keys

```javascript
certificates: {
        wwdr: env.apple_wwdr,
        signerCert: env.apple_signerCert,
        signerKey: {
          keyFile: env.apple_signerKey,
          passphrase: CertificatePaths.applePassphrase,
        },
      },
```

__Originally posted by @WayneDT in https://github.com/alexandercerutti/passkit-generator/issues/22#issuecomment-948268512__

**Comment by alexandercerutti** [comment]
Hi @WayneDT, thanks for using passkit-generator! How is it failing exactly?

**Comment by WayneDT** [comment]
Thank you for responding so quickly.
I found the issue my PEM conversion to one line string was missing a /n

Regards,
Wayne
________________________________
