### ISSUE TITLE
Cannot Pack Passes. Only PKPasses Instances allowed

### ISSUE THREAD

**Issue by collinsrs** [alexandercerutti/passkit-generator#89]
I'm having some trouble getting my passes generated. I used one of your examples and copied it to see if it would work and generate then I can modify it to build my generation system. The webserver starts but I keep getting the issue "Cannot Pack Pass. Only PKPasses instances allowed". I'm relatively new to JS so any help would really be appreciated! Thanks. My code is below.

```javascript
const fs = require("fs");
const { PKPass } = require("passkit-generator");
const path = require("path");

function getRandomColorPart() {
	return Math.floor(Math.random() * 255);
}
const express = require('express'); 
const app = express();
app.use(express.json());

app.listen(8080, "0.0.0.0", () => {
	console.log("Webserver started.");
});

async function generatePass(props) {
	const [iconFromModel] = await Promise.all([
		fs.readFileSync(
			path.resolve(
				__dirname,
				"./icons/icon@1x.png",
			),
		),
		//getCertificates(),
	]);

	const pass = new PKPass(
		{},
		{
			wwdr: "./certs/wwdr.pem",
			signerCert: "./certs/signercert.pem",
			signerKey: "./certs/signerkey.pem",
			signerKeyPassphrase: "redacted",
		},
		{
			...props,
			description: "storecard",
			passTypeIdentifier: "pass.com.re.redacred,
			serialNumber: "204020",
			organizationName: "Me Me",
			teamIdentifier: "1001049NSJ",
			foregroundColor: `rgb(${getRandomColorPart()}, ${getRandomColorPart()}, ${getRandomColorPart()})`,
			labelColor: `rgb(${getRandomColorPart()}, ${getRandomColorPart()}, ${getRandomColorPart()})`,
			backgroundColor: `rgb(${getRandomColorPart()}, ${getRandomColorPart()}, ${getRandomColorPart()})`,
		},
	);

	pass.type = "storeCard";
	pass.setBarcodes({
		message: "12323",
		format: "PKBarcodeFormatPDF417",
	});

	pass.headerFields.push(
		{
			key: "header-field-test-1",
			value: "Unknown",
		},
		{
			key: "header-field-test-2",
			value: "unknown",
		},
	);

	pass.primaryFields.push(
		{
			key: "primaryField-1",
			value: "NAP",
		},
		{
			key: "primaryField-2",
			value: "VCE",
		},
	);


	pass.addBuffer("icon.png", iconFromModel);
	pass.addBuffer("icon@2x.png", iconFromModel);
	pass.addBuffer("icon@3x.png", iconFromModel);

	return pass, err => {
            if (err) {
                console.log(eror);
            }
        };
} 
  app.route("/pkpasses/:modelName").get(async (request, response) => {
	const passName =
		request.params.modelName +
		"_" +
		new Date().toISOString().split("T")[0].replace(/-/gi, "");

	try {
		const passes = await Promise.all([
			generatePass(request.body || request.params || request.query),
			generatePass(request.body || request.params || request.query),
			generatePass(request.body || request.params || request.query),
			generatePass(request.body || request.params || request.query),
		]);

		const pkpasses = PKPass.pack(...passes);

		response.set({
			"Content-type": pkpasses.mimeType,
			"Content-disposition": `attachment; filename=${passName}.pkpass`,
		});

		const stream = pkpasses.getAsStream();

		stream.pipe(response);
	} catch (err) {
		console.log(err);

		response.set({
			"Content-type": "text/html",
		});

		response.send(err.message);
	}
});
```

**Comment by collinsrs** [comment]
I tried to add the code the normal way, I'm sorry it's not formatting correctly.

**Comment by alexandercerutti** [comment]
Hey @collinsrs, thanks for using passkit-generator!
I can guess the issue is that you have changed the code in `generatePass` above with this:

```
	pass.addBuffer("icon.png", iconFromModel);
	pass.addBuffer("icon@2x.png", iconFromModel);
	pass.addBuffer("icon@3x.png", iconFromModel);

	return pass, err => {
        if (err) {
            console.log(eror);
        }
```

You are returning a function `err => void`, not a pass instance as expected. For this reason I can guess you are have issues. I don't what you were hoping to achieve with that function after the return.

Don't worry about the formatting, I've taken care of it.

**Comment by collinsrs** [comment]
Thanks. That fixes the previous error, but with the same code minus the error function (removed), I am getting this message when I try to call the endpoint:

`Invalid PEM formatted message.`

Any Ideas? Thanks

**Comment by alexandercerutti** [comment]
...but are you providing them?
In your previous code, `getCertificates` is commented and you are passing paths as certificates (wwdr, signerCert, signerKey) instead of their content. Genuinely asking, what made you think you can pass paths?

Before performing code changes to the example, I suggest you to:
  - Generate first a valid pass with the examples as-is (all the instructions are available in examples' README)
  - Read the API reference document, so you can understand better thing

Let me know if you have further questions.

**Comment by alexandercerutti** [comment]
Also, let me add the following comment: PKPasses is a new technology available starting from iOS 15, but as you can read in the comment at the top of Pkpasses example, you might have difficulties in testing a result. It seems to be working only in Safari, but it is BUGGED AF (see the comment in example file for screenshots).
I've already tried to report the issue to Apple, but still didn't have received any response back (iOS 15 has been one of the buggest releases I've experienced).

I suggest you to try with another example.

**Comment by collinsrs** [comment]
Thank you so much for your help! I downloaded the example and got that working and am now creating my own. You were right with the PKPasses. When I wanted to download the file to my computer and send as an email it wouldn't work, but accessing from my iPhone's safari worked with no issues. Thanks again!

**Comment by alexandercerutti** [comment]
@collinsrs great to hear! But didn't you experience the issue I talked about, when getting multiple passes from Safari?
