### ISSUE TITLE
Multi ticket creation

### ISSUE THREAD

**Issue by teawithfruit** [alexandercerutti/passkit-generator#9]
Hey.
Is it possible to use your lib for multi ticket creation?
I would like to create a pkpass file with two or more tickets in it.

Thanks

**Comment by alexandercerutti** [comment]
You mean something like this?

![photo_2019-01-21_12-38-33](https://user-images.githubusercontent.com/5442545/51472375-8ddf9800-1d79-11e9-9e01-7b49ece87d28.jpg)

**Comment by teawithfruit** [comment]
Right, I mean something like this. :)
I would like to create something like this with different QR-Codes and with different text field contents.

**Comment by alexandercerutti** [comment]
Technically you have to create two different passes with override the property `groupIdentifier` (manually or via the package). [Look at this](
https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW5) and look at the requirements specified near the key.

**Comment by teawithfruit** [comment]
Ok, thank's for the information.
So it is not possible to create one pkpass file with two passes inside? I think about the possability that the person which will open the file have both passes immedeiatly in their wallet without the creation of two files. If I'am right, I've seen that before by some airlines.

**Comment by alexandercerutti** [comment]
Nope. A pkpass is only one pass. I sincerely don't know how it work. Maybe they automatically do two requests. I found [this reply](https://stackoverflow.com/a/24913354) on StackOverflow. You may find it interesting.

**Comment by teawithfruit** [comment]
Then it seems like I'm wrong.
Thank you for the answer.

**Comment by alexandercerutti** [comment]
You are welcome! I'm closing this issue okay? If you have any other doubts related to this, feel free to re-open it again. 😉
