### ISSUE TITLE
joi_1.default.binary is not a function

### ISSUE THREAD

**Issue by kani-tech** [alexandercerutti/passkit-generator#90]
Hi I am trying to use this package and have followed all of the outlined steps.

When I try to use the function I get this error 

`joi_1.default.binary is not a function`

**Comment by alexandercerutti** [comment]
Hey there @kani-tech, thanks for using passkit-generator!

Seems like Joi has not been installed correctly. Can you check if Joi is available in your node_modules folder please?

If not, can you try again to install the dependencies?

Let me know!

**Comment by kani-tech** [comment]
Thank you for your reply, I see that joi exists in my package.json file.

I have tried uninstalling and installing it as well

**Comment by kani-tech** [comment]
For more context
<img width="1090" alt="Screen Shot 2021-11-22 at 1 00 43 PM" src="https://user-images.githubusercontent.com/64444910/142911982-2afb507e-9446-4f2f-b03f-3dfdae03cab5.png">


I have stored my certificates/keys in an object of strings as such
<img width="521" alt="Screen Shot 2021-11-22 at 1 01 49 PM" src="https://user-images.githubusercontent.com/64444910/142912126-05b3eb81-06b3-40f5-81b7-21ae43115b2d.png">

**Comment by alexandercerutti** [comment]
That's kinda weird: the versions are the same.

Can you paste the whole error stack trace? Are you sure it comes from passkit-generator?

Have you tried to remove your package-lock.json or at least check in it which version it is trying to install?

**Comment by kani-tech** [comment]
It is the same version in the package-lock.json, I have tried to remove it as well. I will try going through the steps again

**Comment by alexandercerutti** [comment]
The steps shouldn't be an issue, though. There must be something else. You can try debugging by using `node --inspect-brk your file.js`.

Let me know if you find something.

**Comment by kani-tech** [comment]
I reinstalled everything and it seems to be working now. Working through the rest of the steps trying to get around an undefined error. Thank you for your support!

**Comment by alexandercerutti** [comment]
Okay great, have fun 😄
Closing
