### ISSUE TITLE
Anyway to use this with Nodejs v12.16.1?

### ISSUE THREAD

**Issue by ilaipi** [alexandercerutti/passkit-generator#93]
Maybe some reasons I can't upgrade my nodejs version, is it possible? Thanks

**Comment by alexandercerutti** [comment]
Hi @ilaipi, thanks for (trying) using Passkit-generator!

Node 12 is not (anymore?) an LTS and it is pretty old, so you should try to upgrade to the most recent LTS version 14 or 16 maybe.
Passkit-generator might still work on node 12 but it has not been tested. I don't know the errors you are experiencing.

Anyway I suggest you using NVM for managing npm and node versions.

**Comment by ilaipi** [comment]
I have met many errors when start my server: ( the same errors when I use node v14.18.2 in my development )

![image](https://user-images.githubusercontent.com/1689135/144746377-616bb504-8c7f-48d1-97a3-6d5b7322ddef.png)

**Comment by alexandercerutti** [comment]
This is definitely not a problem with the node version nor with passkit-generator. I don't know which is your configuration, commands and so on, but you are somehow attempting to make node read .d.ts files, which are declarations for Typescript projects, instead of using (only?) javascript files.
